### ISSUE TITLE
bug report: 文章页底部间距问题

### ISSUE THREAD

**Issue by scaldstack** [yrccondor/mdx#1]
提交评论时有个小圆点

**Comment by yrccondor** [comment]
间距已知是边距设置问题，只要存在2篇及以上文章即可解决。下一版本将会修复该问题。
提交评论的样式问题仍在确认来源，后续版本将会修复

**Comment by yrccondor** [comment]
v1.5.0 版本已发布，此问题已于 commit #c48e6aa 修复。
