### ISSUE TITLE
建议更改“推荐文章”内容

### ISSUE THREAD

**Issue by CNOliverZhang** [yrccondor/mdx#10]
建议把首页“推荐文章”的文章来源由最新文章改成随机文章或最热门文章，因为首页文章列表也是由新到旧排列，推荐文章也显示最新文章显得较为重复

**Comment by yrccondor** [comment]
目前在后台可以设置展示在“推荐文章”的文章分类，只有特定分类的文章会被显示。如果输入的分类名不存在才会显示最新文章
