### ISSUE TITLE
BUG报告，主题无法正常工作。

### ISSUE THREAD

**Issue by minibird** [yrccondor/mdx#102]
这个主题真好！感谢作者的奉献！
在此报告错误。
环境信息如下：
centos7
Apache 2.4.6
mariadb 5.5.64
PHP 7.2.27
wordpress 5.4中文版
原主题：2019
已启用插件：Akismet Anti-Spam、Image Watermark、Rank Math SEO、StartWP Extended、SyntaxHighlighter Evolved、UpdraftPlus-备份/恢复、Watermark、Wordfence Security。
错误现象：
1、本来首页是最新的多篇文章，但启用主题后首页只显示了最新一篇的标题，内容无显示。
2、点击首页最新一篇文章的标题，报错提示”您的站点遇到了致命错误。“
3、MDx主题设置时，想更改首页图片，在媒体库中选择已经上传的图片时，无法选中。
4、启用了抽屉菜单，但是点击首页左上角的菜单图标，无任何反应，没有弹出抽屉菜单。
5、点击首页右上角搜索图片，无任何反应。

其他说明：其他主题运行正常。启用MDx后可以看到MDx主题的配置菜单。
需要的话可以通过您方便的其他方式配合您排查bug。
根据您的提示参考 https://doc.flyhigher.top/mdx/zh-CN/tech/php-errors/#mb_strimwidth
我搜索了php.ini，没找到”;extension=mbstring“。只看到Dynamic Extension一类的设置参数，都注释掉未启用；还有[mbstring]下所有设置也被注释掉了。

**Comment by yrccondor** [comment]
请参考 https://stackoverflow.com/questions/28739892/centos-7-cant-install-php-mbstring-extension

```
sudo yum install php-mbstring
```

**Comment by minibird** [comment]
> 
> 
> 请参考 https://stackoverflow.com/questions/28739892/centos-7-cant-install-php-mbstring-extension
> 
> ```
> sudo yum install php-mbstring
> ```
开启了error模式，确实是这个问题，报错如下：Fatal error: Uncaught Error: Call to undefined function mb_strimwidth() in /var/www/html/minibird/wp-content/themes/mdx/functions.php:340 Stack trace: 
#0 /var/www/html/minibird/wp-content/themes/mdx/template-parts/content-1.php(5): mdx_get_post_excerpt(Object(WP_Post), 250) 
#1 /var/www/html/minibird/wp-includes/template.php(725): require('/var/www/html/m...') 
.......
安装了mbstring，但是不知道怎么开启此功能。
php.ini中添加
extension=mbstring
或者：
extension=mbstring.so
都不成功。
系统中搜索*mbstring*，好像也没找到这个文件。

**Comment by yrccondor** [comment]
你可以通过 `php -m` 命令检查是否成功安装。
如果你在使用 apache，你可能需要重启 httpd。

**Comment by minibird** [comment]
谢谢您的帮助，是因为mbstring没安装成功。现在已经正常工作了！
多谢多谢！
