### ISSUE TITLE
Wrong translation?

### ISSUE THREAD

**Issue by x-Felix** [yrccondor/mdx#105]
<img width="204" alt="Screen Shot 2020-04-17 at 14 35 43" src="https://user-images.githubusercontent.com/25091279/79532557-db4fcf80-80b8-11ea-929c-f25e4d52437e.png">
I tried to reply a user comment. But the English translation is not really correct. 
Should be 'Reply', not 'Replied'. 
Thanks.

**Comment by yechs** [comment]
Will look at it later today

**Comment by yechs** [comment]
@yrccondor BTW is there anything we can do about the title [here](https://www.xfelix.com/2020/01/speed-up-wordpress-site-by-using-cloudflare-workers-edge-cache/)?

It breaks into a newline in the middle of a word...

![image](https://user-images.githubusercontent.com/49149993/79552268-63d86b00-80cd-11ea-83cc-b9c455421b44.png)

**Comment by yrccondor** [comment]
@yechs oh it's because:

https://github.com/yrccondor/mdx/blob/e138fba931a9b64f4a2e5a102d823d30d7068e25/style.css#L220-L222

It's for titles in Chinese. I'm going to find a better solution.

**Comment by yrccondor** [comment]
@yechs btw "6 hoursago" missed a space. "ago" is in

https://github.com/yrccondor/mdx/blob/e138fba931a9b64f4a2e5a102d823d30d7068e25/functions.php#L275

**Comment by yechs** [comment]
> 
> @yechs btw "6 hoursago" missed a space. "ago" is in
> 
> https://github.com/yrccondor/mdx/blob/e138fba931a9b64f4a2e5a102d823d30d7068e25/functions.php#L275

Noted, I'll go add a space before "ago"

**Comment by yechs** [comment]
Fixed in 9ef9b1f
