### ISSUE TITLE
Long title (Latin lang) display issue

### ISSUE THREAD

**Issue by x-Felix** [yrccondor/mdx#107]
<img width="647" alt="Screen Shot 2020-04-17 at 19 36 39" src="https://user-images.githubusercontent.com/25091279/79555574-2bdc2280-80e3-11ea-85cb-079a34203be0.png">
这个问题是 @yechs 访问我的网站时留下的评语中提及的。

非中文的文章主题，如果长度超过浏览器显示宽度，在自动换行的处理上有些问题，会造成一个单词四分五裂。比如上面的截图。using和cache应该都是一个单词，简单粗暴的直接换行在显示上有些不妥。

这个问题在台式机浏览器上不明显，但是在手持设备小屏浏览器上就显得突出了。不知道是否有比较好的解决方法，多谢。

**Comment by yechs** [comment]
@yechs oh it's because:

https://github.com/yrccondor/mdx/blob/e138fba931a9b64f4a2e5a102d823d30d7068e25/style.css#L220-L222

It's for titles in Chinese. I'm going to find a better solution.

_Originally posted by @yrccondor in https://github.com/yrccondor/mdx/issues/105#issuecomment-615139184_

**Comment by yechs** [comment]
话说我翻了一下 [MDN 的 文档](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)

似乎 `break-all` 对于 CJK 字符是不起作用的……？那是不是直接改成 `word-break: normal` 就可以了w？

**Comment by yrccondor** [comment]
这条规则的本意是为了处理单词过长导致溢出的问题，因为中文情况下标题里的英文过长的概率不大，我就这么写了，的确不太妥当。

现在看来应该 `overflow-wrap: break-word;` 就够了。

**Comment by yrccondor** [comment]
Fixed in b309d5e
