### ISSUE TITLE
Material Design Login Page not compatible with Two Factor auth

### ISSUE THREAD

**Issue by x-Felix** [yrccondor/mdx#108]
![7EB9D7A6-A520-4E49-B5E3-2870AA0059B1](https://user-images.githubusercontent.com/25091279/79574551-acab1680-8103-11ea-87f0-72ee5b18aba7.jpeg)

Just let you know the new Material Design login page not compatible with Wordpress Two-Factor plugin. On iOS Safari no display of token submit button which may potentially lock user out.

**Comment by yrccondor** [comment]
"Material Design login page" is not guaranteed to be compatible with all plugins but only WP-WebAuthn.
I'll take a look at this plugin to check if it's possible to add compatibility.
