### ISSUE TITLE
开启Lazyload后导致图片前有空白出现

### ISSUE THREAD

**Issue by SunSi12138** [yrccondor/mdx#110]
版本：mdx1.9.10
问题描述：在mdx主题功能中开启速度/SEO轻度LazyLoad的模式下文章第一张图片前将会产生大段空白，影响使用

网页的源码：
![image](https://user-images.githubusercontent.com/54728594/81620500-a1a38780-941e-11ea-9304-e5e50c1d7d04.png)

而不开启LazyLoad的情况下对应的是这样的：
![image](https://user-images.githubusercontent.com/54728594/81620541-b849de80-941e-11ea-94da-ef0bc3af2b9a.png)

而且这个问题只会出现在文章内第一张图片上，请教一下是怎么回事如何解决呢？

**Comment by yrccondor** [comment]
看起来似乎是其他插件修改了图片加载，和 mdx 的lazyload 冲突了。mdx 的 lazyload 对第一张图片没有特殊优化，你可以尝试使用 seo 重度的 lazyload 模式来避免问题。
此外目前 mdx 对于新编辑器的支持的确不是很好，还有些问题，我正在努力优化。

**Comment by SunSi12138** [comment]
嗯排查出问题了，wordpress后台没有安装其他修改样式的插件，根据出问题的html猜测是与nginx的pagespeed的图片优化冲突了，关闭pagespeed功能后在速度优先模式下也正常了，然后开启空白就回来了。

**Comment by SunSi12138** [comment]
嗯排查出问题了，wordpress后台没有安装其他修改样式的插件，根据出问题的html猜测是与nginx的pagespeed的图片优化冲突了，关闭pagespeed功能后在速度优先模式下也正常了，然后开启空白就回来了。

**Comment by yrccondor** [comment]
那可能只能关闭 lazyload 了
