### ISSUE TITLE
兼容使用 PWA 插件的建议

### ISSUE THREAD

**Issue by debuginn** [yrccondor/mdx#111]
MDx 主题中针对于 MDx文章区块设计，默认是开启新的标签页，可否将此处的设计改为 当前标签页打开新的文章

**Comment by yrccondor** [comment]
想了下的确是当前页面打开更合理，稍后做修改。

**Comment by debuginn** [comment]
补充意见，针对访问者留言备注了自己网站站点的，显示留言的时候，点击留言者名称，他的站点按照从新标签页打开，保持自己的站点在开启状态，而不是覆盖自己的站点开启留言者的站点，我认为这样对自己站点及访问者比较友好

**Comment by debuginn** [comment]
因为是一种类型的问题 我就写到了同一个 Issues中

**Comment by yrccondor** [comment]
一方面我的想法是大部分链接都保留在当页打开的默认行为，访客可以自行选择是否要在新标签页打开；另一方面评论作者的链接其实是由 WordPress 输出的，我想保留这一默认行为。因此第二条可能不会做改动。

**Comment by debuginn** [comment]
好的 了解了
