### ISSUE TITLE
与WP Editor.md插件katex公式兼容问题

### ISSUE THREAD

**Issue by llllhy** [yrccondor/mdx#115]
文章编辑页面的预览部分公式显示是正常的，但是文章发布后的公式显示错误，公式的样式仍为katex代码，并没有被解析。
![image](https://user-images.githubusercontent.com/37238105/84383053-28b26e00-ac1e-11ea-9916-5b0edb075f55.png)

**Comment by yrccondor** [comment]
@llllhy 大概率是插件的问题，请检查插件输出及浏览器是否有报错。MDx 与 katex 及 mathjax 插件均兼容
