### ISSUE TITLE
modify 一言 API 接口更改

### ISSUE THREAD

**Issue by debuginn** [yrccondor/mdx#117]
2018 v1 接口，开始稳定提供。占用域名： v1.hitokoto.cn
目前一言接口弃用之前的版本，可以使用上面的域名继续使用
[https://developer.hitokoto.cn/sentence/](https://developer.hitokoto.cn/sentence/)

**Comment by yrccondor** [comment]
@debuginn MDx 使用的就是 v1.hitokoto.cn 啊...有出什么问题吗

**Comment by debuginn** [comment]
奥奥 我看错了 域名正确 但是返回给我们的 response 格式不一样了

**Comment by yrccondor** [comment]
已确认
