### ISSUE TITLE
Long links do not wrap properly

### ISSUE THREAD

**Issue by yechs** [yrccondor/mdx#120]
## 问题描述

对于长链接而言，不能很好的处理换行问题

## 截图

**这是编辑器中的输入：**
![image](https://user-images.githubusercontent.com/49149993/87250450-50cb0200-c454-11ea-9378-6c3ca06fea27.png)

---

**这是渲染出的结果：**
可以看到文章在链接前后都换行了，无法很好地融入进文章正文中
而且链接 onhover 的下划线只在最下面一行（整个 inline-block 的最下方）中出现
![image](https://user-images.githubusercontent.com/49149993/87250241-0bf29b80-c453-11ea-89bc-755d446f9ae6.png)

---

## 推测相关代码：
上游 mdui.min.css 中的 `display: inline-block`
![image](https://user-images.githubusercontent.com/49149993/87250031-f5981000-c451-11ea-9d22-a4dc03b3d74d.png)

## 可能的解决方案：

加一个 `display: inline` 的 rule？但这样会使得 onhover 下划线完全不显示

**Comment by yechs** [comment]
可以参考 https://blog.shuye.dev/2020/07/%E8%BF%99%E6%98%AF%E4%B8%80%E7%AF%87%E6%B5%8B%E8%AF%95%E6%96%87%E7%AB%A0/

**Comment by yrccondor** [comment]
为了产生下划线动画，这似乎是无法避免的。受到 CSS 限制，目前没有找到比较合适的解决方案，我只能尽量改进。

**Comment by yrccondor** [comment]
由于没有更好的解决方案，我决定在新版本中加入一个 `mdx-article-long-link` class，用于将长链接显示为 `inline` 并适当降级下划线动画。对于长链接，用户可以手动添加这一 class，其他链接将保持原样。

如果有更好的方案请随时告知。
