### ISSUE TITLE
[Suggestion]希望能够自定义Github API的地址

### ISSUE THREAD

**Issue by Zxilly** [yrccondor/mdx#121]
众所周知，Github的api在国内基本上是不存在的，短链接小卡片无法显示，我通过反代解决了这个问题，但是每次更新都要重新修改两个js文件，可否添加一个选项，使用PHP来自动生成这两个文件呢？

**Comment by yrccondor** [comment]
据我目前的了解，github api 的连通性在大陆并没有很差，加上需要访问 github 的用户一般都会自备工具，因此目前看起来有这一需求的用户应该比较少。我 **可能** 会加入一个配置文件以供手动配置。
