### ISSUE TITLE
Localisation issue

### ISSUE THREAD

**Issue by x-Felix** [yrccondor/mdx#128]
The default index page has Chinese character left in English environment. 

`<i class="mdui-icon material-icons seaicon">&#xe8b6;</i> 搜索什么...`

This causes Google Search result shows combination of Chinese character and English. 
<img width="539" alt="Screen Shot 2020-08-28 at 10 23 08" src="https://user-images.githubusercontent.com/25091279/91507564-85b5ea00-e918-11ea-97c1-d0c99a25904a.png">

**Comment by yechs** [comment]
I think this bug is already fixed in commit https://github.com/yrccondor/mdx/commit/2e38a66d4375b7feafdd1ff0f69d3a23372a3b31#diff-828e0013b8f3bc1bb22b4f57172b019dL61-R68.

The fix should be shipped with v2 releases or you can apply the patch manually

**Comment by yrccondor** [comment]
Already fixed 2 months ago, will be shipped later.
