### ISSUE TITLE
当一个文章有两个相同的MDx文章信息卡，第二个似乎无法显示

### ISSUE THREAD

**Issue by MagmaBlock** [yrccondor/mdx#129]
rt，当一个文章有两个相同的MDx文章信息卡，第二个会一直加载，始终无法加载出来。如果删除第一个第二个就能显示
演示界面：https://magma.ink/mdxbug/
主题中的文章信息卡比起wp本来的要好看多了，但是经常会有一直加载的bug太难受了
![Screenshot_2020-09-01-12-40-19-725_com mmbox xbrowser pro](https://user-images.githubusercontent.com/61128045/91795693-e151e180-ec50-11ea-9ff7-a51f6735b182.jpg)
![Screenshot_2020-09-01-12-40-42-605_com mmbox xbrowser pro](https://user-images.githubusercontent.com/61128045/91795695-e2830e80-ec50-11ea-8a50-c8e87dcd3aaa.jpg)
刚开始研究建站没有开发能力，您的主题提供了很大的帮助！非常感谢

**Comment by yrccondor** [comment]
此功能设计在设计之初考虑到一篇文章内插入两个相同的文章信息卡的情况很少会发生，就在代码中使用文章的 URL 来区分各个文章信息卡，导致这样插入文章信息卡会出现问题。
此问题将会在 2.0 修复。
