### ISSUE TITLE
PHP7.2.5启用主题提示数值错误

### ISSUE THREAD

**Issue by FamioGit** [yrccondor/mdx#13]
错误提示：Warning: A non-numeric value encountered
解决办法：mdx/functions.php，393行
原文：`$src = str_replace($wp_version, $wp_version + 37.45, $src);`
改为：`$src = str_replace($wp_version, intval($wp_version) + intval(37.45), $src);`

原因参考：[https://blog.csdn.net/fdipzone/article/details/78659784](https://blog.csdn.net/fdipzone/article/details/78659784)

**Comment by yrccondor** [comment]
感谢，的确是个问题。不过，我已经提交了更合适的解决方案来以此解决主题更新后的缓存问题（commit aa0c69b），下次更新时即可修复。
