### ISSUE TITLE
求支持代码显示

### ISSUE THREAD

**Issue by 1812z** [yrccondor/mdx#132]
其它主题都有代码高亮+整合为一个模块了，但是这个主题没有，可是又不想换....
还是说我操作不对？

**Comment by RSSYLY** [comment]
@1812z 你可以试试 wordpress 插件: Code Syntax Block

**Comment by yrccondor** [comment]
代码高亮不是一个主题必须的功能，使用插件更加合适

**Comment by 1812z** [comment]
> 代码高亮不是一个主题必须的功能，使用插件更加合适

哦哦，我去看看
