### ISSUE TITLE
问题提交

### ISSUE THREAD

**Issue by iammsf** [yrccondor/mdx#133]
5.3版本的WP，最新版的MDx，imgbox不生效，无论是在手机端还是PC端都无法点击放大图片。
此外，使用Enlighter插件，插件功能完全失效。。。。

**Comment by yrccondor** [comment]
将图片链接设置为“媒体文件”，imgbox 才会在这张图片上生效；
我也在用 Enlighter，插件在我的站点上工作正常。

MDx 并没有深入修改 WordPress 功能，绝大部分插件都不应该出现问题。

**Comment by iammsf** [comment]
我也奇怪。特意换了个主题进行测试，Enlighter依旧不起效。我再排查一下，感谢作者

**Comment by iammsf** [comment]
![IMG_20201111_185140](https://user-images.githubusercontent.com/22583624/98802913-fb791e80-244e-11eb-934a-e3b9a0d2bb9b.jpg)
是这样的吗？还是不行😲

**Comment by yrccondor** [comment]
![image](https://user-images.githubusercontent.com/14820835/98803489-cde0a500-244f-11eb-9fb0-f46f55c9be35.png)

**Comment by iammsf** [comment]
太感谢啦，我以为是只要添加图片就可以了，原来要额外添加一个链接的🤗

**Comment by yrccondor** [comment]
因为考虑到有些图片可能不需要 imgbox，所以只有添加了指向“媒体文件”链接的图片才会启用 imgbox
