### ISSUE TITLE
表格排版鬼畜

### ISSUE THREAD

**Issue by ChrisKimZHT** [yrccondor/mdx#134]
![image](https://user-images.githubusercontent.com/49368462/98934801-93ddd480-251d-11eb-83e0-051d3ddad09c.png)

**Comment by ChrisKimZHT** [comment]
表格右侧全部是空白，我试了下，内容越多表格越长，不会自动补全整个页面

**Comment by ChrisKimZHT** [comment]
哦，主题短代码是正常的诶，就是wordpress内置的表格区块有问题

**Comment by ChrisKimZHT** [comment]
还有就是链接不会自动换行，如果在手机上查看排版就会出现问题，看了下作者你的博客也有这个问题，应该不是个例

**Comment by yrccondor** [comment]
表格问题与 WordPress 版本有关，下次更新尽可能修复；
链接不换行与浏览器的换行策略有关，我已经尽量处理了，主要是强制换行在某些情况下并不合适，会造成错误断句。最好的方案是链接显示描述性文本并指向目标地址

**Comment by ChrisKimZHT** [comment]
> 表格问题与 WordPress 版本有关，下次更新尽可能修复；
> 链接不换行与浏览器的换行策略有关，我已经尽量处理了，主要是强制换行在某些情况下并不合适，会造成错误断句。最好的方案是链接显示描述性文本并指向目标地址

恩，作者加油！

**Comment by yrccondor** [comment]
hi，可以给我一个表格显示不正确的示例吗？具体生成的 html 或者线上页面都可以

**Comment by gooodan** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/25093770/103970763-f82ab680-51a3-11eb-83c6-a2efe996a29a.png">
HI,我这目前也遇到这个问题，进来看到其他小伙伴也遇到了，我的Wordpress版本为5.6

**Comment by yrccondor** [comment]
2.0 将修复此问题。
![image](https://user-images.githubusercontent.com/14820835/104021948-921d4e00-51fa-11eb-834c-90835a346fdd.png)

**Comment by debuginn** [comment]
我看了一下  主要是因为 wordpress 古腾堡处理了一下表格，导致与mdx渲染不一致

**Comment by yrccondor** [comment]
已于 6d8b219 修复并发布
