### ISSUE TITLE
页末提示样式及音频区块与主题不符

### ISSUE THREAD

**Issue by RSSYLY** [yrccondor/mdx#137]
如图，这个似乎不太像MDx中其他的区块...
![Screenshot_20210102-113928_Firefox Beta](https://user-images.githubusercontent.com/59304676/103450321-ba371980-4cef-11eb-841a-a0fc0ba94471.jpg)
还有这个音频区块，感觉强迫症要犯了，希望作者抽空看下这个问题，或者若有相关插件也可。
![Screenshot_20210102-113900_Firefox Beta](https://user-images.githubusercontent.com/59304676/103450342-fbc7c480-4cef-11eb-961b-5d7d92397133.jpg)

**Comment by RSSYLY** [comment]
@RSSYLY 我错了，那个音乐播放条是浏览器的

**Comment by yrccondor** [comment]
音频播放直接调用浏览器原生播放器了，MDx 未作处理；
文章末提示确实是设计就是这样，我会在下次更新时尽量优化

**Comment by RSSYLY** [comment]
@yrccondor 支持大佬

**Comment by yrccondor** [comment]
文章末提示已于 b310ac8 优化
![image](https://user-images.githubusercontent.com/14820835/104127337-8a95aa80-539c-11eb-8cd0-1bb77b3655ef.png)
![image](https://user-images.githubusercontent.com/14820835/104127340-8cf80480-539c-11eb-9e0e-7ac80af4c0ed.png)
