### ISSUE TITLE
MDx 2.0 translation

### ISSUE THREAD

**Issue by yrccondor** [yrccondor/mdx#139]
MDx 2.0 is almost ready! Now following translations need to be updated:

- [x] en_US (#138 #140)
- [x] zh_TW
- [x] zh_HK
- [x] tr_TR (#143 #145)

Hi @evayde we will be very happy if you can help us to add German (de_DE) translation.

**Comment by SakuraPuare** [comment]
Already done?

**Comment by yrccondor** [comment]
> Already done?

Yes, we are going to release 2.0 in few days.

**Comment by SakuraPuare** [comment]
> > Already done?
> 
> Yes, we are going to release 2.0 in few days.

👍
