### ISSUE TITLE
无法正常显示MDUI的对话框

### ISSUE THREAD

**Issue by PFiS1737** [yrccondor/mdx#146]
代码一样，在此主题中无法正常显示。
Github pages中: 
![Screenshot_2021-01-23-23-02-37.png](https://i.loli.net/2021/01/23/kHf2zoFERrV16qa.png)
![Screenshot_2021-01-23-22-57-47.png](https://i.loli.net/2021/01/23/o1uDC6KWr2VjYHX.png)
WordPress中: 
![Screenshot_2021-01-23-23-02-25.png](https://i.loli.net/2021/01/23/73srIuPQXCenMHT.png)
![Screenshot_2021-01-23-22-57-37.png](https://i.loli.net/2021/01/23/n2akvygcLQRWhjS.png)

**Comment by yrccondor** [comment]
主题结构限制，请使用 MDUI 预定义对话框
