### ISSUE TITLE
开启了“友情链接随机顺序”后，友链页面不正常显示了

### ISSUE THREAD

**Issue by ChrisKimZHT** [yrccondor/mdx#147]
开启了“友情链接随机顺序”后，友链就不显示了，页面里啥都没有。
![1](https://user-images.githubusercontent.com/49368462/105635206-d10aff00-5e9c-11eb-8481-bdf2ebd54fdb.png)

**Comment by yrccondor** [comment]
已于 627868f 修复，过几天推送 2.0.1。
目前可以通过将链接添加到任意分类目录来解决，这个问题只会在没有链接分类目录时出现。
