### ISSUE TITLE
网站自定义报错

### ISSUE THREAD

**Issue by shiyingqi** [yrccondor/mdx#149]
不知道什么原因，在多台机器上手动，自动都试了，更新主题后会发生wp本身的错误 = =

Fatal error: Cannot redeclare get_preferred_from_update_core() (previously declared in /usr/local/wordpress/wp-admin/includes/update.php:17) in /usr/local/wordpress/wp-admin/includes/update.php on line 25
此站点遇到了致命错误，请查看您的站点管理邮件地址来获得指引。

Fatal error: Cannot redeclare get_preferred_from_update_core() (previously declared in /www/wwwroot/wp-admin/includes/update.php:17) in /www/wwwroot/wp-admin/includes/update.php on line 16
此站点遇到了致命错误，请查看您的站点管理邮件地址来获得指引。

**Comment by yrccondor** [comment]
确实遇到了，但我的三个版本一致的 wordpress 实例中有一个没有出现这个问题，另两个复现了，报错也有点奇怪，暂时还没有什么头绪，可能需要一些时间排查

**Comment by shiyingqi** [comment]
通过局部的更替，使用旧版本的functions.php能够正常使用

猜测引发错的文件为functions.php

具体原因未知。

**Comment by yrccondor** [comment]
已经确认问题由 835220f 引入，但还在寻找报错原因

**Comment by yrccondor** [comment]
已于 2.0.1 修复
