### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by liuran001** [yrccondor/mdx#15]
所有的小图标均显示乱码，网站[liuran001.top](https://liuran001.top)，大佬来看看   
![](https://yun.liuran001.top/?/images/2018/06/18/IMG_20180618_112558.png)

**Comment by yrccondor** [comment]
图标不显示是因为你没有配置正确的 `MIME` 规则，你需要为字体文件手动配置。此外，我这里无法加载 CSS 和 JS 文件，似乎是 HTTPS 的跨域问题造成的，不过手头只有手机就没自己看，你需要自己检查一下。
