### ISSUE TITLE
新版本图片选择器不能插入链接

### ISSUE THREAD

**Issue by ChrisKimZHT** [yrccondor/mdx#150]
主题更新新版本图片选择器后不能直接输入图片链接了，也就是不能插入外链了。
![image](https://user-images.githubusercontent.com/49368462/107489067-29434000-6bc3-11eb-97c4-a02f40e74441.png)
如果能让这个输入框可以手动输入就好了

**Comment by SakuraPuare** [comment]
复议，同样的在 MDx主题-样式-首页 里的 首页图片 也希望可以手动输入地址。
虽然可以曲线救国，先点 使用必应美图 再把网址输入进去。

**Comment by ChrisKimZHT** [comment]
> 复议，同样的在 MDx主题-样式-首页 里的 首页图片 也希望可以手动输入地址。
> 虽然可以曲线救国，先点 使用必应美图 再把网址输入进去。

哈我发现可以直接用浏览器开发者工具，找到那个输入框的代码，删去readonly那一个参数，然后就可以直接输入了...（算是曲线救国了）

**Comment by yrccondor** [comment]
花了点时间研究了一下，WordPress 新的图片选择器非常难以扩展，图片选择器里有“从 URL 插入”功能但没法启用，目前只能去掉文本输入框的 `readonly` 属性。稍后更新
