### ISSUE TITLE
首页默认图片显示异常？

### ISSUE THREAD

**Issue by HanHan233** [yrccondor/mdx#151]
![Screenshot_2021-02-17-17-58-42-669_com microsoft emmx](https://user-images.githubusercontent.com/64469437/108187822-da108880-7149-11eb-9861-152cfee2754e.jpg)
![Screenshot_2021-02-17-17-58-54-154_com microsoft emmx](https://user-images.githubusercontent.com/64469437/108187848-df6dd300-7149-11eb-9ef8-496fd1af2e50.jpg)
![Screenshot_2021-02-17-17-59-50-733_com microsoft emmx](https://user-images.githubusercontent.com/64469437/108187928-f3193980-7149-11eb-8ea1-16a7849ed5f2.jpg)

如题：我在主题内已经设置文章默认特色图片，但是网站内仍然显示主题内置的默认特色图片

**Comment by yrccondor** [comment]
已确认，下次更新修复

**Comment by HanHan233** [comment]
好的，加油（）
