### ISSUE TITLE
优化抽屉菜单列表项

### ISSUE THREAD

**Issue by haohaostudio** [yrccondor/mdx#152]
希望能将默认的列表项样式改为（或变成可选项）
![image](https://user-images.githubusercontent.com/22652631/109015432-11ee7180-76f0-11eb-8b93-265f81db6b02.png)
现在的列表项也许对移动端不太友好

**Comment by yrccondor** [comment]
在关闭 MD2 样式的情况下，抽屉菜单的样式应该于此一致。
请确保你已经参考[主题文档](https://doc.flyhigher.top/mdx/zh-CN/config/menu/)正确设置了菜单。
