### ISSUE TITLE
文章列表的样式能否设定为圆角

### ISSUE THREAD

**Issue by lyuan77** [yrccondor/mdx#153]
如标题，在首页的文章列表模式下，边框样式偏直角 ↓

![image](https://user-images.githubusercontent.com/48856873/109962890-b55e0880-7d26-11eb-9eb6-e17a460f28cd.png)

在文章页面，边框样式偏圆角 ↓

![image](https://user-images.githubusercontent.com/48856873/109962687-74fe8a80-7d26-11eb-85d5-1e0ccdd1ed50.png)

是否可以修改首页的文章列表边框，从直角变为圆角，这样的视觉效果会好些。

**Comment by PFiS1737** [comment]
在设置中打开 "样式 - 全局 - Material Design 2"选项即可，或者根据喜好添加额外的CSS样式(border-radius)

**Comment by lyuan77** [comment]
问题已解决，感谢答复，很抱歉因为没有仔细阅读文档而打扰到你。
