### ISSUE TITLE
新增首页幻灯片样式的无图模式

### ISSUE THREAD

**Issue by BingYanchi** [yrccondor/mdx#157]
![image](https://user-images.githubusercontent.com/36477925/111065147-37062100-84f3-11eb-9714-418be4432691.png)

希望增加一种幻灯片样式，和 “现代” 类似，但是不显示图片，就和没有设定特色图片的文章一样。

期望的效果：
![image](https://user-images.githubusercontent.com/36477925/111065229-a4b24d00-84f3-11eb-9ed3-73756a2986ef.png)

**Comment by BingYanchi** [comment]
顺带一提：考不考虑在幻灯片模式下，支持自动轮换，就是自动隔多少秒（希望自定义时间）翻页

**Comment by yrccondor** [comment]
1. 如果你不介意文章摘要也不显示的话，选择“朴素”样式就不会显示图片了。我会考虑在下个版本中新增一种样式。
2. 目前的自动切换间隔是 5s，应该符合大部分人的需求了。我的想法是，如果允许自定义，可能会让设置太过琐碎。

**Comment by BingYanchi** [comment]
> 1. 如果你不介意文章摘要也不显示的话，选择“朴素”样式就不会显示图片了。我会考虑在下个版本中新增一种样式。
> 2. 目前的自动切换间隔是 5s，应该符合大部分人的需求了。我的想法是，如果允许自定义，可能会让设置太过琐碎。

1. 我的想法确实是希望显示文章摘要。
2. 时间间隔我是觉得有点短了，或许给个间隔的选择框也可以。
