### ISSUE TITLE
一点小瑕疵

### ISSUE THREAD

**Issue by BingYanchi** [yrccondor/mdx#158]
![image](https://user-images.githubusercontent.com/36477925/111066500-62403e80-84fa-11eb-9fd1-739bb34c3986.png)

或许... 在白色背景的情况下并不明显，那放大了看：
![image](https://user-images.githubusercontent.com/36477925/111066529-8734b180-84fa-11eb-95ea-3c5954a89246.png)

再到暗色模式看看，这样更明显：
![image](https://user-images.githubusercontent.com/36477925/111066544-961b6400-84fa-11eb-9a99-2dd212459402.png)

缩小了看它有多明显：
![image](https://user-images.githubusercontent.com/36477925/111066594-bfd48b00-84fa-11eb-8508-c82ddf8130fd.png)

可能是一个小疏忽吧

**Comment by yrccondor** [comment]
这不是疏忽。句号前后都是链接，而句号不是。MDx 对链接和文本定义了不同的样式，这里只是遵循了 WordPress 的 HTML 结构和 MDx 的 CSS

由于 MDx 本身没有对多用户做优化，这里的样式可能不会被优化，你可以自定义 CSS 来覆盖掉这里的样式
