### ISSUE TITLE
当首页设置为幻灯片时，仍然加载了必应美图

### ISSUE THREAD

**Issue by BingYanchi** [yrccondor/mdx#160]
![image](https://user-images.githubusercontent.com/36477925/112660666-a46d6680-8e90-11eb-90c0-5e92590bb1e7.png)

这是我在 Google PageSpeed Insights 上测试时看到的。

尽管我已经设置了首页为幻灯片，抽屉栏也使用了媒体库的图片，但是他仍然加载了必应美图。

注：
功能 - 首页 - 首页样式：普通
功能 - 首页 - 首页图片：`--BingImagesActivated(0)--`
功能 - 首页 - 首页头部展示内容：幻灯片

**Comment by shiyingqi** [comment]
我在多个实例中测试，并未能复现此问题
等作者答复叭

**Comment by BingYanchi** [comment]
似乎设置的所有首页图片，都会被这么提示。

但我仍然疑惑的是，已经在看不到的必应美图的情况下，仍然会加载。

**Comment by shiyingqi** [comment]
你这么说我就懂了 = = 
可以试试把内容删去 留下空格

**Comment by BingYanchi** [comment]
> 你这么说我就懂了 = =
> 可以试试把内容删去 留下空格

我试过了，但是他不让我留空

**Comment by shiyingqi** [comment]
> > 你这么说我就懂了 = =
> > 可以试试把内容删去 留下空格
> 
> 我试过了，但是他不让我留空

留个   空格

**Comment by BingYanchi** [comment]
> > > 你这么说我就懂了 = =
> > > 可以试试把内容删去 留下空格
> > 
> > 
> > 我试过了，但是他不让我留空
> 
> 留个 空格

似乎这是可行的

**Comment by yrccondor** [comment]
确实是加载了，因为对应的元素没有被移除，下个版本会有所优化

**Comment by yrccondor** [comment]
已于 b95bbe5 修复
