### ISSUE TITLE
能不能添加几个gravatar 镜像源

### ISSUE THREAD

**Issue by hibobmaster** [yrccondor/mdx#164]
默认的gravatar地址被墙了，国内用户访问显示的头像都成方块了～
望作者大大能不能考虑加入这个功能呢？

**Comment by debuginn** [comment]
支持，现在被墙的挺厉害的  最好是可以配置

**Comment by Mas0nShi** [comment]
可以考虑使用第三方插件。
例如 ：WP-China-Yes

**Comment by hibobmaster** [comment]
WP-China-Yes感觉这个插件侵入性太强，且很多功能用不上～
想保证简洁一些
像[kratos ](https://github.com/vtrois/kratos)等主题都是集成在主题里的

这里只是希望开发者能考虑支持一下，不打算添加也没关系哈
