### ISSUE TITLE
菜单前面图标不显示，是不是字体文件Font跨域权限这块的问题？新手不懂谢谢！

### ISSUE THREAD

**Issue by a77596191** [yrccondor/mdx#167]
![image](https://user-images.githubusercontent.com/83082384/115893686-15516f80-a48b-11eb-9558-bbb012a1887e.png)

**Comment by yrccondor** [comment]
是，字体文件需要和页面在同一个源下，或有正确的 `Access-Control-Allow-Origin` 头

**Comment by a77596191** [comment]
好的，谢谢。那我这种应该怎么解决，不太会。
