### ISSUE TITLE
在表格样式上，与WP Editor.md的兼容性问题

### ISSUE THREAD

**Issue by daxiaamu** [yrccondor/mdx#171]
使用markdown制表后mdx下表现如图

![image](https://user-images.githubusercontent.com/29529412/117744749-d289e880-b23b-11eb-80ef-d35e93c646b0.png)

使用WordPress自带主题二〇二一，效果如下
![image](https://user-images.githubusercontent.com/29529412/117744869-08c76800-b23c-11eb-82d1-3cebf8c6c9ed.png)

同样的markdown文本在其他的网站的效果
![image](https://user-images.githubusercontent.com/29529412/117744948-32808f00-b23c-11eb-9355-1a5db7f3327a.png)

**Comment by yrccondor** [comment]
可以给一个 editor.md 生成的表格的在线示例吗
