### ISSUE TITLE
[Bug]抽屉菜单显示异常

### ISSUE THREAD

**Issue by HanHan233** [yrccondor/mdx#174]
如图，设置子菜单后无法正常显示，我推测是浏览器API变更的问题，但是后续测试推翻了我的结论（即非浏览器api变更问题）
所以我后来又推测是MDx使用的CSS库的api变更
但是我在切换不使用CDN之后也一样显示异常（我在。InPrivate设置无法截图)
以下是截图
# 仪表板设置
![仪表板设置](https://user-images.githubusercontent.com/64469437/118283038-840d7000-b501-11eb-9d03-4c81a00699b5.jpg)
# 异常的显示效果
![异常的显示效果](https://user-images.githubusercontent.com/64469437/118283059-896aba80-b501-11eb-9076-55e7d0d08e1e.jpg)
环境信息 - Microsoft Edge Dev Android
![环境信息 - Microsoft Edge Dev Android](https://user-images.githubusercontent.com/64469437/118283065-8b347e00-b501-11eb-9dcb-ddd9df3a0238.jpg)
# 在旧版Edge上仍然显示异常
![在旧版Edge上仍然显示异常](https://user-images.githubusercontent.com/64469437/118283587-1d3c8680-b502-11eb-9d91-fce828c1bb44.jpg)
# 旧版Edge版本信息
![旧版Edge版本信息](https://user-images.githubusercontent.com/64469437/118283600-1e6db380-b502-11eb-8045-c57f14d7ab06.jpg)
希望Axton能够尽快修复，谢谢（话说啥时候发稳定release

**Comment by yrccondor** [comment]
可以给一个能复现的线上地址我看一下吗？

这几天正在着手开始修最近发现的问题

**Comment by HanHan233** [comment]
> 可以给一个能复现的线上地址我看一下吗？
> 
> 这几天正在着手开始修最近发现的问题

# 一个可以复现的地址
![image](https://user-images.githubusercontent.com/64469437/118335565-847a2b00-b542-11eb-9e8a-82f2367578cd.png)
# 这个复现地址我将会保留一周时间
![image](https://user-images.githubusercontent.com/64469437/118335628-a4115380-b542-11eb-8f74-a24541864b0e.png)
# 浏览器版本信息
![image](https://user-images.githubusercontent.com/64469437/118335718-d327c500-b542-11eb-9de8-5d9e2fa144aa.png)

**Comment by HanHan233** [comment]
我尝试过了把所有插件都禁用后完全重载，但是似乎没有效果

**Comment by HanHan233** [comment]
另外多发现了一个问题，就是“加载更多”没了
![Screenshot_2021-05-15-18-32-11-479_com microsoft emmx dev](https://user-images.githubusercontent.com/64469437/118357295-f9357f80-b5ab-11eb-99a1-88a9c2dd4a79.jpg)

**Comment by HanHan233** [comment]
我现在觉得问题出在WordPress自动更新到5.7.2的原因

**Comment by PFiS1737** [comment]
> 我现在觉得问题出在WordPress自动更新到5.7.2的原因

应该不是，我也是自动更新的，刚新弄了一个折叠菜单，没有问题

**Comment by PFiS1737** [comment]
一个正常的collapse列表应该是如下图的: 
![Screenshot_2021-05-15-20-15-33](https://user-images.githubusercontent.com/69380732/118360567-f1310c00-b5ba-11eb-80a7-09368754dcd8.png)
而您的却是这样: 
![Screenshot_2021-05-15-20-14-32](https://user-images.githubusercontent.com/69380732/118360587-0a39bd00-b5bb-11eb-8a14-ad9378c262fa.png)
所以应该检查一下设置之类的，或看看有没有提供列表优化的插件与该主题冲突
 
(我目前用的版本是v2.0.1)

**Comment by HanHan233** [comment]
我没搞美化啊，而且我今天下午才重装了一次MDx

**Comment by yrccondor** [comment]
线上地址似乎已更新，我自己未能成功复现这个问题🤔

感觉像是和其他插件冲突了

**Comment by HanHan233** [comment]
> 线上地址似乎已被更改，我自己未能成功复现这个问题🤔
> 
> 感觉像是和其他插件冲突了

刚刚被我搞炸了正在恢复（

**Comment by HanHan233** [comment]
> 线上地址似乎已被更改，我自己未能成功复现这个问题🤔
> 
> 感觉像是和其他插件冲突了

恢复完了，现在你可以复现了（

**Comment by yrccondor** [comment]
似乎是有其他插件修改了 window 对象的 `DOMContentLoaded` 事件，导致 MDx 所有依靠 `DOMContentLoaded` 事件触发的逻辑都没有成功触发。暂时怀疑是 cf 的 rocket loader 导致的

**Comment by yrccondor** [comment]
搜了下 https://changchen.me/blog/20190923/cloudflare-display-issue/ 发现 rocket loader 确实会导致 `window.DOMContentLoaded` 不可用

**Comment by HanHan233** [comment]
> 搜了下 https://changchen.me/blog/20190923/cloudflare-display-issue/ 发现 rocket loader 确实会导致 `window.DOMContentLoaded` 不可用
> 
> MDx 对于 js 文件的加载顺序是有性能方面的考量的，且逻辑加载依赖于 js 载入顺序，不需要也不能使用 rocket loader 来继续优化

好的，谢谢开发者，已经关闭了，现在能用了
（此图片仅表明，帖子中的所有问题都得到解决，非渲染问题）
![Screenshot_2021-05-16-00-16-06-449_com microsoft emmx dev](https://user-images.githubusercontent.com/64469437/118370792-f3f02900-b5db-11eb-963e-158b87e776b3.jpg)
