### ISSUE TITLE
表格简码无法识别

### ISSUE THREAD

**Issue by baipin** [yrccondor/mdx#177]
现在表格简码中的换行符无法识别转换，见图:
![Screenshot_20210608_094148](https://user-images.githubusercontent.com/39830783/121109275-cf374c00-c83d-11eb-9eff-8cfe67c8add2.jpg)

**Comment by yrccondor** [comment]
能方便提供一下所用编辑器的具体信息吗？我无法重现在经典编辑器和区块编辑器中重现这个问题

**Comment by baipin** [comment]
> 能方便提供一下所用编辑器的具体信息吗？我无法重现在经典编辑器和区块编辑器中重现这个问题

无论是区块编辑器还是经典编辑器，都是这样。
问题已经强制解决，我直接用h5把表格码出来了(||๐_๐)。
=========
为了将问题复现，我直接用文档中的短代码。
1.如果用“简码”区块，则运作正常。
2.如果在区块编辑器里直接输入，则会异常。（应该是区块编辑器自动分割的结果）
![Screenshot_20210613_110559](https://user-images.githubusercontent.com/39830783/121794006-67b33f00-cc37-11eb-89aa-8fda1e9f815d.jpg)
![Screenshot_20210613_110750_com android chrome](https://user-images.githubusercontent.com/39830783/121794035-9e895500-cc37-11eb-891d-4689d8ba9fdd.jpg)
3.如果使用经典编辑器插件，键入:
`[mdx_table header="true"]捐助者

金额

日期

-----

微信匿名

¥10.00

2017.11.11

-----

*晨

¥2.33

2017.11.12

-----

Zyb

¥11.13

2017.11.13

-----

*清华

¥50.00

2018.1.1[/mdx_table]`
同样出问题:
![Screenshot_20210613_111115_com android chrome](https://user-images.githubusercontent.com/39830783/121794092-296a4f80-cc38-11eb-918d-c337c0f5b116.jpg)
![Screenshot_20210613_110750_com android chrome](https://user-images.githubusercontent.com/39830783/121794093-2b341300-cc38-11eb-879a-364166071b04.jpg)
综上，只有用古腾堡“简码”区块，还才运作正常。

**Comment by yrccondor** [comment]
在这两种情况下，编辑器都会试图格式化你输入的内容。在区块编辑器中，请使用简码区块或直接使用原生的表格区块；在经典编辑器中，请在文本模式下输入表格短代码。对于编辑器在其他情况下做的格式化，MDx 无能为力

**Comment by baipin** [comment]
> 在这两种情况下，编辑器都会试图格式化你输入的内容。在区块编辑器中，请使用简码区块或直接使用原生的表格区块；在经典编辑器中，请在文本模式下输入表格短代码。对于编辑器在其他情况下做的格式化，MDx 无能为力

谢谢。但是，值得注意的是，纵使经典编辑器使用纯文本模式，也无法正常转换。

**Comment by yrccondor** [comment]
在纯文本模式中请注意换行，多余的空行会导致识别错误；而通常在可视化模式中输入的内容在切换到纯文本模式后会出现空行
