### ISSUE TITLE
图片加载问题

### ISSUE THREAD

**Issue by PIPIPIKa** [yrccondor/mdx#18]
最近图片查看出问题了,我用手机电脑查看写过的文章,总是加载不出图片,但是在编辑界面是正常的.
[`试过chrome,firefox,以及IE;不知道是哪里的问题,前几天还正常,附上网站地址[blog.pikaka.top](url)
![look](https://user-images.githubusercontent.com/39107465/49077741-085ad280-f277-11e8-9193-ae217c8b8e9a.png)
编辑界面:
![edit](https://user-images.githubusercontent.com/39107465/49077795-2d4f4580-f277-11e8-9b8c-a4766c8d1cfa.png)
 我试过引用百度的外链,也是同样无法加载,这种情况只在这个主题上出现过.

**Comment by PIPIPIKa** [comment]
好的 我试一下




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            lei gao
                            
                            
                                
                                    邮箱：gaoleiytu@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2018年11月27日 20:25，AxtonYao 写道： 你似乎使用了第三方 LazyLoad 插件？MDx 自带 LazyLoad 功能，会和其他插件冲突的，你可以检查下。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yrccondor/mdx","title":"yrccondor/mdx","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/yrccondor/mdx"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yrccondor in #18: 你似乎使用了第三方 LazyLoad 插件？MDx 自带 LazyLoad 功能，会和其他插件冲突的，你可以检查下。"}],"action":{"name":"View Issue","url":"https://github.com/yrccondor/mdx/issues/18#issuecomment-442040131"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yrccondor/mdx/issues/18#issuecomment-442040131",
"url": "https://github.com/yrccondor/mdx/issues/18#issuecomment-442040131",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [yrccondor/mdx] 图片加载问题 (#18)",
"sections": [
{
"text": "",
"activityTitle": "**AxtonYao**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@yrccondor",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"yrccondor/mdx\",\n\"issueId\": 18,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"yrccondor/mdx\",\n\"issueId\": 18\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/yrccondor/mdx/issues/18#issuecomment-442040131"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 416619599\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by PIPIPIKa** [comment]
谢谢你,是我自己的问题，我装了一个Jetpack，然后里面有一个lazyloading的功能，我给选上了，不好意思，是我操作失误。

**Comment by yrccondor** [comment]
😃
