### ISSUE TITLE
功能建议：加入评论验证码

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#180]
建议加入评论发布时进行人机验证
推荐使用：

- reCaptcha
- 腾讯云验证码
- 图形验证码
- 化学反应方程式验证码（？）

**Comment by PFiS1737** [comment]
感觉必要性不是很大。这应该可以用一些插件解决  (

**Comment by AH-dark** [comment]
> 这应该可以用一些插件解决(

兼容性不好

**Comment by yrccondor** [comment]
此功能不属于主题的功能范畴，更适合使用插件解决。

MDx 一直都在尽可能避免加入与主题无关的功能以避免过于臃肿。不过你可以告知你希望使用的的验证码插件的名称，MDx 会尝试对其进行适配。

**Comment by AH-dark** [comment]
> 此功能不属于主题的功能范畴，更适合使用插件解决。
> 
> MDx 一直都在尽可能避免加入与主题无关的功能以避免过于臃肿。不过你可以告知你希望使用的的验证码插件的名称，MDx 会尝试对其进行适配。

- 腾讯云验证码：https://cn.wordpress.org/plugins/tencentcloud-captcha/
- reCaptcha：https://cn.wordpress.org/plugins/google-captcha/

**Comment by Li-Zi-stu** [comment]
> 此功能不属于主题的功能范畴，更适合使用插件解决。
> 
> MDx 一直都在尽可能避免加入与主题无关的功能以避免过于臃肿。不过你可以告知你希望使用的的验证码插件的名称，MDx 会尝试对其进行适配。

> *All In One WP Security：https://cn.wordpress.org/plugins/all-in-one-wp-security-and-firewall/
这个插件总和了所有的防御措施

**Comment by AH-dark** [comment]
> > 此功能不属于主题的功能范畴，更适合使用插件解决。
> > MDx 一直都在尽可能避免加入与主题无关的功能以避免过于臃肿。不过你可以告知你希望使用的的验证码插件的名称，MDx 会尝试对其进行适配。
> 
> *All In One WP Security：https://cn.wordpress.org/plugins/all-in-one-wp-security-and-firewall/
> 这个插件总和了所有的防御措施

问题在于：UI不适配
