### ISSUE TITLE
php 8.0 环境下运行异常

### ISSUE THREAD

**Issue by Jkkoi** [yrccondor/mdx#182]
在各种地方报错

![photo_2021-07-02_09-58-06](https://user-images.githubusercontent.com/39653010/124209530-464dc080-db1c-11eb-9834-8beae9b05c14.jpg)
主题设置页面

![image](https://user-images.githubusercontent.com/39653010/124209623-76955f00-db1c-11eb-816d-10a05ae03137.png)
新建文章页面

PHP Version `8.0.7`
System `Linux localhost 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u2 (2019-08-08) x86_64`

**Comment by yrccondor** [comment]
这是正常行为，warning 不会影响主题的正常运行，建议调低生产环境中的 PHP 报错等级。这不是 PHP 8 相关的问题

**Comment by Jkkoi** [comment]
@yrccondor 
在 php8 环境下，首页的 bing 图片无法正常加载
![image](https://user-images.githubusercontent.com/39653010/124210787-9d549500-db1e-11eb-8269-26b0d6fd585e.png)
`PS： header 把报错信息盖住了，我把 header 删了`
但是在 php74 中可以正常加载

**Comment by yrccondor** [comment]
你的 PHP 配置不允许你的 PHP 读取系统证书，导致无法验证 Bing 的 HTTPS 连接。把证书路径添加到 `open_basedir` 即可

**Comment by Jkkoi** [comment]
但是让我迷惑的是，我的 php7 和 php8 的配置文件是一样的
![image](https://user-images.githubusercontent.com/39653010/124212343-6469ef80-db21-11eb-84e3-dbdef8ee89b0.png)

难道 php8 多了限制？

**Comment by Jkkoi** [comment]
而且很迷惑的一点是 ，Wordpress 自身的 插件下载/主题下载 是没有问题的

**Comment by yrccondor** [comment]
可以提供一下安装插件的列表吗？我注意到抛出错误的 PHP 文件路径与一般的不同

**Comment by Jkkoi** [comment]
@yrccondor php8 的 还是 php7 的

**Comment by yrccondor** [comment]
PHP 8 下 WordPress 的插件列表

**Comment by Jkkoi** [comment]
![image](https://user-images.githubusercontent.com/39653010/124215277-4c489f00-db26-11eb-9bd6-bbf83b5b6703.png)

**Comment by yrccondor** [comment]
检查了这个插件，未能在我的开发环境中复现这个问题，应该是 PHP 配置相关的问题

**Comment by AH-dark** [comment]
改curl，ssl验证设置false，就好了吧（）
