### ISSUE TITLE
Bug：MDx会更改wordpress的版本号函数

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#184]
装载MDx后，使用get_bloginfo('version')、$wp_version等方法获取的版本号并非wordpress版本号而变成了MDx的版本号

**Comment by yrccondor** [comment]
无法复现问题，且 MDx 中没有修改 WordPress 版本号的相关逻辑，请检查下其他插件

**Comment by AH-dark** [comment]
现在只要我在代码中引用了5.7.2（wordpress版本号）都会替换成2.0.1.a3f91e2，也只有MDx有这个版本信息并且commit能对上

**Comment by yrccondor** [comment]
页面中载入的 css 和 js 的 URL 中的版本号会被 MDx 替换为 MDx 版本号，本意是为了在 MDx 更新后相关文件的缓存可以被正常刷新；MDx 没有其他版本号相关的逻辑，不会替换 WordPress 的版本号，我在我的环境中也无法复现这个问题

**Comment by AH-dark** [comment]
若其他插件在引入js、css文件时须携带wordpress版本号以适配的时候，wordpress版本号被替换为MDx版本号会导致无法正常引入
比如我要引用
<https://cdn.jsdelivr.net/gh/wordpress/wordpress@5.7.2/wp-includes/js/admin-bar.js>
时会被自动替换为
<https://cdn.jsdelivr.net/gh/wordpress/wordpress@2.0.1.a3f91e2/wp-includes/js/admin-bar.js>
导致文件无法正常访问

建议您使用更好的方式以刷新缓存等，此方式会影响到其他插件的js、css加载

**Comment by yrccondor** [comment]
这一块逻辑确实有问题。MDx 本意是不修改 URL 中的版本号，只替换 URL query（即 ? 后的内容），且只会替换 ver 参数，现在是发现 ver 参数后对 URL 中的版本号进行了统一替换。

https://github.com/yrccondor/mdx/blob/5b840825f6d8e5ecde005233861defdba39f1ee8/functions.php#L288-L297

临时方案是将 292 行替换为

```php
$src = str_replace('ver='.$wp_version, 'ver='.get_option('mdx_version_commit'), $src);
```

稍后修复。
