### ISSUE TITLE
在关于页等“页面”的位置上，搜索框会无法显示

### ISSUE THREAD

**Issue by eventhorizonsky** [yrccondor/mdx#185]
问题出在了js文件夹下的page.js，不过我不能定位在哪里，有一段函数将opacity设置为了0导致了这个问题

**Comment by AH-dark** [comment]
本来想提PR的，但你那个代码格式实在是……
---
在 页面 需要引入```/js/js.js```

**Comment by yrccondor** [comment]
> 本来想提PR的，但你那个代码格式实在是……
> 
> 在 页面 需要引入`/js/js.js`

老项目了，牵扯到的东西比较多，体谅一下...

在页面中引入 `js.js` 可能会产生其他错误。这是 `page.js` 中的错误，稍后修复。
