### ISSUE TITLE
建议：增加自定义扩展链接功能

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#187]
建议允许自定义链接头部尾部以实现更高的可扩展性

例如

- 封面图片加后缀链接
- 文章内缩略图加后缀链接
- 文章内原图加后缀链接
- 页面链接加后缀
- js、css加后缀
- 文档文件加后缀

**Comment by AH-dark** [comment]
就可以配合使用存储桶的文件操作等

**Comment by yrccondor** [comment]
@AH-dark 其实建议插件做这件事

**Comment by AH-dark** [comment]
> @AH-dark 其实建议插件做这件事

有些交互统计啥的需要，插件会大幅减速

**Comment by AH-dark** [comment]
自然，非必要性，仅建议

**Comment by yrccondor** [comment]
用插件吧，实在没有类似插件自己写一个也不困难。MDx 可能不会考虑加入此功能
