### ISSUE TITLE
Bug：部分模块延迟加载影响体验

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#189]
文章中添加“下载”“按钮”等古腾堡编辑器模块时，MDx会自动将其转换为MDUI的按钮样式等，但会延迟一小下，影响用户体验

**Comment by yrccondor** [comment]
这个其实没有什么太好的办法，mdx 要等到全部 DOM 载入才能开始初始化这些元素，在此之前只能通过添加一部分 css 来覆盖默认样式，但这又会与 mdui 的样式重复，增加代码体积

**Comment by yrccondor** [comment]
会尽量优化

**Comment by yrccondor** [comment]
> 而且多按钮那个，间距太小，可以看下

多按钮可以给一个例子吗？我用官方的多按钮区块没有发现太大问题

**Comment by AH-dark** [comment]
lazyload的锅，按钮不放页面加载的第一浏览位置就好了（看不见就好了）
