### ISSUE TITLE
New editor 'Gutenberg' support

### ISSUE THREAD

**Issue by yrccondor** [yrccondor/mdx#19]
Now WordPress 5.0 released with a new editor 'Gutenberg'. We scheduled to support this editor but lack of time. Contact me or simply comment to this issue if you want to help us. Anyway, THANKS!

WordPress 5.0 已经释出，并带来了新的默认编辑器“Gutenberg”。我计划让 MDx 适配新编辑器，但是这工作量不小，而且我没有太多时间。如果你有意向协助我们进行开发的话，欢迎联系我或直接在此 issue 下留言。感谢！

**Comment by LTDSA** [comment]
我也许能帮上一些忙......这是关于什么方面的编程？

**Comment by yrccondor** [comment]
@LTDSA 大部分是 Javascript，接入新编辑器的 API

**Comment by LTDSA** [comment]
JavaScript的话我不是特别的熟悉，应该只能帮些不是特别紧要的......如果说其他语言我还是可以的（比如C++、HTML什么的）

**Comment by yrccondor** [comment]
@LTDSA 啊没事，感谢

**Comment by LTDSA** [comment]
所以我能帮些什么......

**Comment by syfxlin** [comment]
是开发短代码对应的Gutenberg区块吗？或许我能协助开发。

**Comment by yrccondor** [comment]
@syfxlin 目前需要做的就是将已有的5个短代码转换为 Gutenberg 区块。你可以协助我们吗？

**Comment by syfxlin** [comment]
@yrccondor 表格那个需要吗？只需要重写WordPress自带的表格样式就可以适配了，还是需要开发同短代码一样的区块？

**Comment by yrccondor** [comment]
表格短代码不需要的，毕竟 Gutenberg 已经自带了；去掉表格一共有 6 个短代码，分别是 折叠内容、警告内容、进度指示器、文章卡片、Github 卡片、广告

**Comment by syfxlin** [comment]
@yrccondor 文章卡片、Github 卡片、广告这上个文档中没有，更新一下文档？

**Comment by yrccondor** [comment]
前两者是有的 https://doc.flyhigher.top/mdx/zh-CN/shortcodes/github-info-card/
广告短代码是这次（暂未发布的）更新中新加入的，所以文档没有；不过这个只需要一个占位符就可以了，没有任何参数的

**Comment by syfxlin** [comment]
@yrccondor React不能添加没有data-开头的自定义字段，折叠内容无法添加mdui-panel字段，造成无法折叠和展开，可以利用js修复，修复的方案就是在页面加载完成的时候利用js添加mdui-panel字段

```javascript
document.querySelectorAll('.wp-block-mdx-fold').forEach(item => {
    item.setAttribute('mdui-panel', '');
});
```

**Comment by yrccondor** [comment]
@syfxlin 不能添加 data- 属性的话，可以问一下你觉得最合适的解决方案是什么吗？
折叠内容的话，可以额外添加一个 mdx-fold-gutenberg 的 class，我在前端做个判断

**Comment by syfxlin** [comment]
@yrccondor 除广告其他5个都搞定了，广告涉及PHP可能无法制作成区块。。。

![image](https://user-images.githubusercontent.com/28844480/66251573-27be6800-e784-11e9-9812-7bb6e861357e.png)

![image](https://user-images.githubusercontent.com/28844480/66251579-3442c080-e784-11e9-8c17-77dfc65f4e01.png)

**Comment by syfxlin** [comment]
> @syfxlin 不能添加 data- 属性的话，可以问一下你觉得最合适的解决方案是什么吗？
> 折叠内容的话，可以额外添加一个 mdx-fold-gutenberg 的 class，我在前端做个判断

直接把上面那串JS放到合适的JS文件中即可

**Comment by yrccondor** [comment]
@syfxlin 非常感谢！
方便的话现在就发起一个 pr 吧，正好马上要发更新了

**Comment by syfxlin** [comment]
@yrccondor 主题只需要使用build后的文件就可以工作，那源代码要放哪？

**Comment by yrccondor** [comment]
@syfxlin 新建一个 gutenberg-src 之类的文件夹吧，自动构建的时候可以删掉的

**Comment by syfxlin** [comment]
> @syfxlin 非常感谢！
> 方便的话现在就发起一个 pr 吧，正好马上要发更新了

pr已发ヾ(≧▽≦*)o

**Comment by syfxlin** [comment]
@yrccondor 经过测试发现Gutenberg编辑器可以将区块渲染成短代码（[syfxlin/hermit-x-blocks](https://github.com/syfxlin/hermit-x-blocks)），广告短代码也可以制作成区块了，若有需要我可以提一个PR添加广告短代码对应的Gutenberg区块。

**Comment by yrccondor** [comment]
@syfxlin 非常欢迎！
