### ISSUE TITLE
手机端页脚显示错乱

### ISSUE THREAD

**Issue by mtcomic** [yrccondor/mdx#198]
今天更新了PHP7.4版本，使用手机Safari 和移动版chrome浏览下发现页脚显示错乱
目前使用了谷歌自动广告，代码贴于页头处
以下的网站首页截图，使用手机Safari 浏览
打码处为文章标题和网站地址，以及谷歌广告标题
![5D6DB8FC-E6F1-47AC-8F5B-415B43D74674](https://user-images.githubusercontent.com/84577411/132943163-430372d2-7375-449b-8279-bd893c4472e6.jpeg)

谢谢开发者的主题，辛苦了。另外请问新版本什么时候能发布？

**Comment by yrccondor** [comment]
关于错误，可以给一个线上的例子吗？

近两天就会发布一个新版本

**Comment by mtcomic** [comment]
谢谢开发者，辛苦了
可以留一个邮箱吗？我把详细情况发给你。

**Comment by yrccondor** [comment]
我 github 留的邮箱就可以

**Comment by mtcomic** [comment]
可能是我使用的插件年久失修导致在新版本PHP7.4上面出现了问题吧
禁用插件之后测试已经恢复正常
谢谢开发者的帮助，非常感谢
