### ISSUE TITLE
如何将首页改为三列

### ISSUE THREAD

**Issue by zwbao** [yrccondor/mdx#199]

**Comment by yrccondor** [comment]
“三列”指的是？

**Comment by zwbao** [comment]
> “三列”指的是？

就是现在的首页是这样的，两列内容

![image](https://user-images.githubusercontent.com/24564677/133016879-f04650e1-d5df-41c9-b264-208c151aae1d.png)

我是想改为文章以三列在首页呈现

**Comment by yrccondor** [comment]
目前只能在单列和二列中二选一，需要三列可以自行修改文章卡片宽度相关的 css

**Comment by zwbao** [comment]
> 目前只能在单列和二列中二选一，需要三列可以自行修改文章卡片宽度相关的 css

好的，谢谢！
