### ISSUE TITLE
升级1.5.0后的问题

### ISSUE THREAD

**Issue by MarkDeia** [yrccondor/mdx#2]
图片显示不出来、搜索栏不能打开、顶栏消失…
各种问题啊……
貌似上次我升级1.4.1的时候就有图片显示不出来的问题了
换过几台服务器了，只要一切回1.4.0就一切正常，基本可以排除是服务器环境和网络问题

**Comment by yrccondor** [comment]
已经发现是由于在 functions.php 中注册的一条关键 js 没有被成功调用，即将释出1.5.1版本。你也可以下载仓库中的 footer.php 自行替换主题的源文件。

**Comment by yrccondor** [comment]
现在1.5.1版本已经释出，受 CDN 缓存限制，最晚几分钟后即可更新。

**Comment by MarkDeia** [comment]
仍旧不行，问题更加严重了，侧边栏打不开
php报错Parse error: syntax error, unexpected '}', expecting end of file in /wp-content/themes/mdx/footer.php on line 65

**Comment by yrccondor** [comment]
可能因为cdn刷新了错误的版本，你可以编辑  footer.php，将65行开头的 <?php }if 改为 <?php if
详见 commit 9acefaf
