### ISSUE TITLE
能否使状态模式的文章可点击

### ISSUE THREAD

**Issue by jiesou** [yrccondor/mdx#200]
![Screenshot_2021-09-19-08-36-26-585_com.mmbox.xbrowser.pro.png](https://user-images.githubusercontent.com/84175239/133911877-60374d64-8cdc-4c08-88c2-51ff1f16352e.png)

**Comment by AH-dark** [comment]
状态本身就是为了直接体现内容且内容较简洁，没必要点进去看吧

**Comment by jiesou** [comment]
可是你可以从上一篇或者下一篇文章的这里进去。![IMG_20210927_184515.jpg](https://user-images.githubusercontent.com/84175239/134894146-77f61987-9c79-48e9-bc1f-df61506109ac.jpg)
如果有人在里面评论，别人就不能很容易看到
而且这里显示的格式有时会有问题。图片只能显示一半，没法调整大小，也没有 ImgBox
