### ISSUE TITLE
Bug：MDx会更改所以和MDx版本相同的js引用字符串

### ISSUE THREAD

**Issue by AH-dark** [yrccondor/mdx#207]
你他娘的就是个天才 @yrccondor 

在 #184 中，MDx出现了强行修改wordpress版本的问题。根据临时修复方案我进行了修复。

在最新发布的MDx 2.0.2中，MDx出现了强行修改mdx版本号的问题（即所有js、css请求地址中2.0.2会被剔除）

**Comment by AH-dark** [comment]
此时我很想送给你一句你曾说过的话：把这功能交给插件吧

https://github.com/yrccondor/mdx/blob/f6722b5005310dcfce4abdfaaf08d62b16863633/functions.php#L292-L309

**Comment by yrccondor** [comment]
1. 我的博客和开发环境都没有复现此问题
2. MDx 的缓存更新依赖此逻辑，无法拆分为插件

**Comment by AH-dark** [comment]
好吧这是我的锅，我pr写的正则出了问题（）
