### ISSUE TITLE
mdx分享卡片

### ISSUE THREAD

**Issue by Mas0nShi** [yrccondor/mdx#212]
![image](https://user-images.githubusercontent.com/60805843/139610234-ad9cea8c-474c-4c3f-bd51-9a84cb145672.png)
RT，通过控制台可以看到报错，但是不知道是哪里有问题...
    post.js?ver=2.0.2.20a1c53:formatted:978 
           Uncaught (in promise) TypeError: e.default is not a function
        at post.js?ver=2.0.2.20a1c53:formatted:978
    (匿名) @ post.js?ver=2.0.2.20a1c53:formatted:978
    Promise.then(异步)
    q @ post.js?ver=2.0.2.20a1c53:formatted:977

**Comment by yrccondor** [comment]
我无法在开发环境中复现此问题，看起来是对应的 js 没有载入。能否提供一个出问题的链接？

**Comment by Mas0nShi** [comment]
https://blog.shi1011.cn/persummary/1614

**Comment by yrccondor** [comment]
![2021-11-04_14-44-42](https://user-images.githubusercontent.com/14820835/140269542-f441c5fd-b2c6-4a1a-ae07-5c8971f9a066.png)
🤔没有复现此问题

**Comment by Mas0nShi** [comment]
az，在我的手机和电脑上都无法生成分享图……
并且**时常**会有一个跨域访问错误，不仅对于图片资源、js、css似乎都有对应的报错
是否可能是此问题引发……如何解决呢
  
  [Report Only] Refused to load the image 'https://cdn.xxx.cn/2021/01/xxx.jpg' because it violates the following Content Security Policy directive: "img-src 'self' 'unsafe-inline' 'unsafe-eval' data:".
![image](https://user-images.githubusercontent.com/60805843/140292310-1132e23b-ffa0-4ae0-abf4-392ac39e6d05.png)

**Comment by yrccondor** [comment]
> az，在我的手机和电脑上都无法生成分享图…… 并且**时常**会有一个跨域访问错误，不仅对于图片资源、js、css似乎都有对应的报错 是否可能是此问题引发……如何解决呢
> 
> [Report Only] Refused to load the image '[cdn.xxx.cn/2021/01/xxx.jpg](https://cdn.xxx.cn/2021/01/xxx.jpg)' because it violates the following Content Security Policy directive: "img-src 'self' 'unsafe-inline' 'unsafe-eval' data:". ![image](https://user-images.githubusercontent.com/60805843/140292310-1132e23b-ffa0-4ae0-abf4-392ac39e6d05.png)

这个是 CSP 头带来的限制，靠前端无法解决，应该是你的配置问题...

我反复刷新页面，这个头只有一定几率出现，似乎是 CDN 配置问题

**Comment by Mas0nShi** [comment]
> > az，在我的手机和电脑上都无法生成分享图…… 并且**时常**会有一个跨域访问错误，不仅对于图片资源、js、css似乎都有对应的报错 是否可能是此问题引发……如何解决呢
> > [Report Only] Refused to load the image '[cdn.xxx.cn/2021/01/xxx.jpg](https://cdn.xxx.cn/2021/01/xxx.jpg)' because it violates the following Content Security Policy directive: "img-src 'self' 'unsafe-inline' 'unsafe-eval' data:". ![image](https://user-images.githubusercontent.com/60805843/140292310-1132e23b-ffa0-4ae0-abf4-392ac39e6d05.png)
> 
> 这个是 CSP 头带来的限制，靠前端无法解决，应该是你的配置问题...
> 
> 我反复刷新页面，这个头只有一定几率出现，似乎是 CDN 配置问题

确实，这里使用的是腾讯CDN……我也怀疑过是CDN的问题（
另外，我会去排查一下分享这一问题，因为在我未更新mdx前，分享图功能似乎都是正常的。
不管怎么样，感谢你百忙之中抽空处理。
Thank you.

**Comment by Mas0nShi** [comment]
当我更新到了2.0.3，这个问题蜜汁的被解决了……
