### ISSUE TITLE
与Rank Math SEO有冲突

### ISSUE THREAD

**Issue by ZiXia1** [yrccondor/mdx#222]
![image](https://user-images.githubusercontent.com/66472729/148642931-4ca0fcdc-86ee-4885-9181-b42fcdec5042.png)
重复

**Comment by ZiXia1** [comment]
网页标题计算方式为Wordpress默认，没有去更改

**Comment by AH-dark** [comment]
I apologize.
It's a legacy of my previous Pull Request(#210), and I've submitted a new Pull Request(#223) to fix it.
