### ISSUE TITLE
区块图片简介bug

### ISSUE THREAD

**Issue by baipin** [yrccondor/mdx#225]
2.0.3版本中：古腾堡编辑器的"画廊"区块：
当填入图片简介时，应当文字悬浮在图片之上，但此版本却是图片悬浮于文字之上，应该是bug。
![Screenshot_20220218_231320](https://user-images.githubusercontent.com/39830783/154709609-68b62b34-e13e-4e36-8984-afbcb3034561.jpg)

**Comment by yrccondor** [comment]
是 wordpress 5.9 更改了画廊的 HTML 格式，mdx 的 imgbox 暂时没法处理新的格式，冲突了

稍后修复

**Comment by baipin** [comment]
该问题已随wp更新而修复，但是有更大的问题：图片比例不正常

**Comment by yrccondor** [comment]
晚了两年...此问题已经在 7da3ad0 修复，兼容最新版本的 wp，同时支持了 wp 的双色调滤镜功能
<img width="735" alt="2024-08-08_05-35-43" src="https://github.com/user-attachments/assets/b389ea50-3896-4880-90d1-98821ad0d917">
