### ISSUE TITLE
希望添加一个 分类归档 的页面模板

### ISSUE THREAD

**Issue by sukiko789** [yrccondor/mdx#23]
分类归档的模板 有时候会很有用 但并没有在页面模板中发现有该模板 希望添加

**Comment by yrccondor** [comment]
在这个模板中需要展示哪些内容呢？毕竟分类归档页和标签归档页都有的

**Comment by sukiko789** [comment]
展示分类吧…新的wordpress自带的分类归档部件感觉按钮有点小……

**Comment by yrccondor** [comment]
不可用使用分类页面么？

**Comment by sukiko789** [comment]
页面模板只有link postlike tags3个啊……

**Comment by yrccondor** [comment]
你是指 https://flyhigher.top/recommended 这种吗？

**Comment by sukiko789** [comment]
拆分可以让建站者自由选择，合并为观看者省去了时间。如果设计不是很耗时间的话，我个人建议是分开

**Comment by yrccondor** [comment]
已于 7c5978d 添加
