### ISSUE TITLE
菜单能设成鼠标移到位置后自动弹出吗?

### ISSUE THREAD

**Issue by fcying** [yrccondor/mdx#24]
还有能加自动隐藏的侧边栏吗?

东西全放菜单有点麻烦. 弄个能自动隐藏的侧边栏 加点小插件挺好的

**Comment by fcying** [comment]
菜单就是指的抽屉菜单.

侧边栏 是指wordpress 里面的 default sidebar, 在屏幕边缘放个小图标, 移动到小图标上就打开default sidebar

**Comment by yrccondor** [comment]
@fcying 明白了，这个开发可能需要一些时间，我考虑一下

**Comment by fcying** [comment]
感谢~_~
