### ISSUE TITLE
与插件 External Media without Import 的兼容问题

### ISSUE THREAD

**Issue by Wesley1999** [yrccondor/mdx#240]
插件 External Media without Import 用于把外部图像添加到媒体库
使用外部图像作为文章特色图片时，生成分享图无法显示文章特色图片
![image](https://user-images.githubusercontent.com/35622526/181182567-eef32bc6-2e01-4fe5-a0b1-17b267345d8c.png)

**Comment by Wesley1999** [comment]
目前我的做法是隐藏分享按钮，在页脚代码中添加
```html
<style>.mdx-share{display: none} .spanout .material-icons{padding-left: 10px}</style>
```

**Comment by yrccondor** [comment]
如果是外部图像，确实会无法显示。这受到浏览器跨域资源限制，无法解决。之后会添加选项以关闭生成分享图
