### ISSUE TITLE
文章分享bug

### ISSUE THREAD

**Issue by ForeverAndAlways** [yrccondor/mdx#25]
在使用过程中发现，如果文末信息为空时，分享URL中无法正常加入本文URL。
经测试，当文末信息填写为“--PostURL--”，以上分享URL问题解决。
再次删除文末信息后，问题重现。

**Comment by yrccondor** [comment]
文章连接获取相关为已知 Bug，会在稍后修复。

**Comment by yrccondor** [comment]
@ForeverAndAlways 也是已知问题，不过由于“MDx优化”是可用的，这个问题可能会在稍晚修复，不过不会拖太久的

**Comment by yrccondor** [comment]
已分别于 ee8d145 和 bbab3da 修复
