### ISSUE TITLE
Can't access admin panel

### ISSUE THREAD

**Issue by Sn0bzy** [yrccondor/mdx#26]
I can't access this theme's own admin panel. What should I do?

**Comment by yrccondor** [comment]
Any details? What did you do? Which version you are using? Any warning or error? I can't reproduce it anyway, please tell me more about it.

**Comment by Sn0bzy** [comment]
When I click this link > https://prnt.sc/n4wql0 | I see this page > https://prnt.sc/n4wqmt

Also, I can't see any button to access theme panel in Wordpress admin sidebar.

I'm using WordPress 5.1.1 and PHP 7.3.3

**Comment by yrccondor** [comment]
Are you running a multi-user site? Any user with 'edit_themes' permission should be allowed to access this page. It looks like a simple permission problem. Anyway, I'll check this later.

**Comment by Sn0bzy** [comment]
Problem solved, thanks.
