### ISSUE TITLE
怎么实现代码块高亮？

### ISSUE THREAD

**Issue by stmoonar** [yrccondor/mdx#267]
怎么实现代码块高亮？像作者博客里那样的
<img width="801" alt="image" src="https://github.com/yrccondor/mdx/assets/128700661/37fb89f5-dae1-4ff2-ab43-15cec0de7c42">

**Comment by 54853315** [comment]
使用代码区块啊，然后给代码区块指定特殊的class name，比如想显示成yaml就填入`language-yaml`。
