### ISSUE TITLE
使用一段时间后的mdx，首页文章的时间排序有些奇怪

### ISSUE THREAD

**Issue by 54853315** [yrccondor/mdx#268]
## 版 本
mdx：2.0.3
wordpress: 6.3.x

## 具体问题

使用mdx有2年了，去年就发现排序有问题，一直忙活着所以没怎么弄，这阵子有时间了，想来提一个issue。不知道大家有没有头绪（比如`themes/mdx/index.php` 的第几行是关键信息）？

![错乱的时间线排序](https://github.com/yrccondor/mdx/assets/1081252/6b02052a-7031-48db-b7b6-8ea535f90ba0)

可以提供脱敏后的INSERT SQL (posts)。

**Comment by yrccondor** [comment]
如果你依然有问题的话，这里的解释是瀑布流排序是按照纵向距离排序的，越新的文章会越靠上，这个排序有的时候会和从左向右的习惯冲突，但是能保证排序在纵向顺序上一直是对的
