### ISSUE TITLE
Can I change language?

### ISSUE THREAD

**Issue by Sn0bzy** [yrccondor/mdx#27]
Hello,

How can I change language on this theme?

**Comment by yrccondor** [comment]
MDx supports multi-language but English is still being translated. English language file will be published later. You can help us if you want.

**Comment by Sn0bzy** [comment]
I want to help you. I can translate to Turkish.

**Comment by yrccondor** [comment]
Thanks! Can you translate it from Chinese? Thanks a lot.

Besides, if you have a Telegram account, you can contact me on Telegram. https://t.me/AxtonYao
