### ISSUE TITLE
挺不错的

### ISSUE THREAD

**Issue by arkilis** [yrccondor/mdx#3]
就一个小小的意见：中间的网页宽度有点窄：

![image](https://user-images.githubusercontent.com/1528028/34550267-2b08afb4-f15b-11e7-9a10-2bdf1de1b2ac.png)

**Comment by yrccondor** [comment]
max-width: 680px;
在
 https://github.com/yrccondor/mdx/blob/master/style.css#L267
因为开发分辨率不大没想到高分屏看起来这么难受
下次更新会优化下，以及在后台加入控制选项

**Comment by yrccondor** [comment]
此问题已在 commit d60f9dc 修复
