### ISSUE TITLE
使用古腾堡编辑器时，文末信息模块会使排版混乱

### ISSUE THREAD

**Issue by BillChen2000** [yrccondor/mdx#30]
![image](https://user-images.githubusercontent.com/11037722/55699903-77072400-59ff-11e9-87b7-e7ec73fee8dc.png)

如图所示，在使用古腾堡编辑器时，文末的信息编辑会覆盖掉文本内容，无法编辑，并且在下滑页面的时候，整个自定义字段部分都会自行移动。

**Comment by yrccondor** [comment]
默认情况下，这个面板应该位于编辑器的最下方，我测试并不会挡住页面，你可以检查一下你后台 JS 的载入情况，可能是出了问题的。
MDx 并没有对 Gutenberg 编辑器做任何改动——实际上，MDx 对于 Gutenberg 编辑器的支持仍在计划中，你可以加入 #19 的讨论来帮助我们。
