### ISSUE TITLE
首页大图及抽屉菜单顶部图片问题

### ISSUE THREAD

**Issue by RaingoTop** [yrccondor/mdx#32]
RT
请问这两者能否选择性去除？尤其是抽屉菜单顶部图片

**Comment by yrccondor** [comment]
首页大图的话换一种首页样式即可去除（但是色块还在）；抽屉菜单顶部图片暂时不能去除，有这个需求的话我可以在7月更新里加上。

**Comment by RaingoTop** [comment]
谢回复，主要指的就是色块，而且个人感觉抽屉菜单顶部图片确实没有太大作用，能在新版本里加入去除选项更好

**Comment by yrccondor** [comment]
移除抽屉菜单顶部图片的功能已于 7ccdddc 添加；不过首页大图的去除可能要等再下次更新了
