### ISSUE TITLE
这个wordpress主题是免费的吗？

### ISSUE THREAD

**Issue by chineselzh** [yrccondor/mdx#36]
如题，请问这主题是免费使用的吗？如果不是的话，那有什么限制？
谢谢！

**Comment by Sn0bzy** [comment]
MDx根据GPL v3.0许可证分发。没有什么限制。 只是你不能出售和删除页脚链接。 出版商将帮助您。 @yrccondor

**Comment by yrccondor** [comment]
如 @Sn0bzy 所言，MDx 是免费的，使用 GPL V3.0 许可证分发，你需要遵守这个许可证，唯一的附加条件是你必须保留页脚的 "Theme: MDx by Axton" 字样
