### ISSUE TITLE
关于夜间模式的建议

### ISSUE THREAD

**Issue by chineselzh** [yrccondor/mdx#38]
能否支持设置网站一直采用`夜间模式`呢？因为夜间模式太漂亮了，想一直使用夜间械。谢谢！

**Comment by yrccondor** [comment]
会考虑加个选项的

**Comment by Sn0bzy** [comment]
您可以更改主题颜色，例如夜间模式。或者您可以在主题编辑器上设置颜色。

**Comment by yrccondor** [comment]
@Sn0bzy 目前暂时不能直接设置为夜间模式

**Comment by Sn0bzy** [comment]
我尝试过，但它不起作用。对不起，错误的信息。

**Comment by yrccondor** [comment]
已于 1cc16f9 添加此功能
