### ISSUE TITLE
对于一些颜色较浅的主题文本颜色的建议

### ISSUE THREAD

**Issue by BillChen2000** [yrccondor/mdx#39]
很喜欢这个主题，不过对于一些主题来讲，也许将标题部分文本强调色更改为白色会更好看一些，例如 Blue 主题的标题：

![image](https://user-images.githubusercontent.com/11037722/58269909-19fedc00-7dbb-11e9-970e-65c1fcfbfb4d.png)

**Comment by yrccondor** [comment]
这是 Material Design 规范中定义的且由 MDUI 进行实现，MDx 只是遵循了 MDUI 的原始表现。因此短期内我们不会对这一表现进行修改。
你可以通过加载额外的自定义 CSS 来覆盖这一表现。
