### ISSUE TITLE
[附截图]登录状态下顶部显示重叠问题

### ISSUE THREAD

**Issue by Doracoin** [yrccondor/mdx#4]
![default](https://user-images.githubusercontent.com/9206272/34757266-03848116-f60b-11e7-812b-e75706d180fe.png)

**Comment by yrccondor** [comment]
这个问题知道的，但是因为没有特别大的影响一直没有修复，可能会在下面几次更新中修复。目前你可以选择关闭 Admin Bar 来暂时避免这个问题。

**Comment by yrccondor** [comment]
此问题已在 V1.7.2 修复。你可以在后台更新 MDx 来解决此问题。详细见 commit b64ab82

**Comment by Doracoin** [comment]
最新版已修复这个问题，感谢。
