### ISSUE TITLE
[Feature Request]Let users decide whether the link adds the rel="nofollow" attribute in the link management interface? 

### ISSUE THREAD

**Issue by StarryLeo** [yrccondor/mdx#42]
Add an option to let users decide, instead of adding directly:
https://github.com/yrccondor/mdx/blob/107d2433fa4ef1bfea85863c5d5d8fb40ea329b7/functions.php#L237

**Comment by yrccondor** [comment]
Due to the fact that WordPress doesn't support nofollow natively, we are looking for the best way to include this feature in MDx, which takes time.
If it is possible, this feature will be included in the next release.
