### ISSUE TITLE
English i18n Support

### ISSUE THREAD

**Issue by yechs** [yrccondor/mdx#48]
Hi, I'm planning to translate the site into English, and I've checked files inside the `language` directory (`tl_TR.mo` and `tl_TR.po`). 

Would the existing text strings suffice? Or do I need to look for more strings inside the codes?

**Comment by yrccondor** [comment]
@yechs Unfortunately MDx doesn't support English now, and there is no English translation file, but we do have plan to translate MDx into English (and that's in the progress actually). You can help us to translate if that's possible.

**Comment by yechs** [comment]
Sure I'm definitely willing to; how can I get started?

**Comment by yrccondor** [comment]
@yechs Well that's simple. Using POEdit

**Comment by yechs** [comment]
So far I have copied the existing `tl_TR.po` to a new `en.mo`. And I'm planning to edit the Turkish strings to English using POEdit.

Since the translation is already in progress. Is there a way for me to catch up with the current progress (to prevent duplicate effort)?

**Comment by yrccondor** [comment]
Well, no. Because I haven't gotten the translation file yet. But actually we haven't made much progress even on the docs so you can simply translate MDx from the beginning.

**Comment by yechs** [comment]
Sure 😄, I'll start working in my forked repo [yechs/mdx](https://github.com/yechs/mdx) then

**Comment by yrccondor** [comment]
really thanks!
