### ISSUE TITLE
请问如何删除顶部的toolbar 

### ISSUE THREAD

**Issue by namezhouyu** [yrccondor/mdx#5]
toolbar我打算自己用原生写 注：连同toolbar上的搜索和抽屉也去掉

**Comment by yrccondor** [comment]
很抱歉 ToolBar 并不是独立的，在 `index.php` `archive.php` `category.php` `page.php` `page-postlike.php` `page-links.php` `single.php` 中均有相关代码。要移除 ToolBar，可以移除或注释这些文件中的 `header` 元素。由于这个组件功能牵涉较广，这么做可能会导致意料之外的 `Javascript` 错误。最简单的方式是利用 `display: none !important;` 隐藏这个元素。

**Comment by namezhouyu** [comment]
@yrccondor 好的 了解了 谢谢
