### ISSUE TITLE
抽屉菜单详细信息无法显示撇号 '

### ISSUE THREAD

**Issue by yechs** [yrccondor/mdx#50]
在“抽屉菜单详细信息”里输入带有撇号的字符串并保存后，`'`会被自动转义成为 `\'`
猜测是PHP为了防止SQL注入对字符串进行的处理

如图，`apostrophe '` 变成了 `apostrophe \'`

![image](https://user-images.githubusercontent.com/49149993/65867947-e60b7700-e3a9-11e9-8243-29d478470fe7.png)

![image](https://user-images.githubusercontent.com/49149993/65868238-7ea1f700-e3aa-11e9-81cb-a702ff7c69c1.png)

并且转义后的字符串会显示在页面上，如图↓；值得一提的是，“首页格言”没有出现这样的bug

![image](https://user-images.githubusercontent.com/49149993/65868041-1d7a2380-e3aa-11e9-8aad-6c07adba6b9b.png)

PS: “顶部栏自定义名称”出现了相同的bug；

**Comment by yrccondor** [comment]
包含这一修复的更新将在最近几天发布。
如果你希望立即修复的话，你可以在你的站点中按照 3e5038a 手动进行修改。

**Comment by yechs** [comment]
tks
