### ISSUE TITLE
无法正常浏览文章，开启debug报错信息如下，我的数据库版本是8.0

### ISSUE THREAD

**Issue by only-love-yiqiu** [yrccondor/mdx#55]
Warning: mysqli_real_connect(): Headers and client library minor version mismatch. Headers:50560 Library:50642 in /deploy/wordpress/wp-includes/wp-db.php on line 1612

Notice: Undefined index: mdx_install in /deploy/wordpress/wp-content/themes/mdx/functions.php on line 5

**Comment by yrccondor** [comment]
你的 WordPress 没有正确连接到数据库，这不是 MDx 的问题。
从报错来看，你应该尝试更新你的 PHP。
