### ISSUE TITLE
图片无法正常显示

### ISSUE THREAD

**Issue by HodenX** [yrccondor/mdx#57]
如下图，图片无法正常显示，我是用wordpress预览时可以看到的，使用其他主题也没有问题

![image](https://user-images.githubusercontent.com/19523966/68675430-ce233780-0592-11ea-8b2b-c3a18e25db6c.png)

同时还伴随了下面的一些错误：

`Notice: Undefined index: class in /data/home/byu6231680001/htdocs/wp-content/themes/mdx/functions.php on line 359

Notice: Undefined index: class in /data/home/byu6231680001/htdocs/wp-content/themes/mdx/functions.php on line 359

Notice: Undefined index: class in /data/home/byu6231680001/htdocs/wp-content/themes/mdx/functions.php on line 359`

**Comment by yrccondor** [comment]
大多数情况下，由 WordPress 编辑器插入的图片会带有 `class`，而 MDx 会通过解析 `class` 来实现一些特殊功能，如 LazyLoad 和 ImgBox。空的 `class` 属性的确会引起 Notice，且可能导致图片无法显示。我正在做进一步检查，顺利的话几天之内应该可以修复。
顺便问一下，你是通过什么方式插入图片的呢？

**Comment by yrccondor** [comment]
已于 2d1111e 修复，1.9.2 更新已包含此修复
