### ISSUE TITLE
感谢创作如此好的作品

### ISSUE THREAD

**Issue by swgqq** [yrccondor/mdx#58]
您的作品非常好，很新颖，特别是搜索功能等，很多都是我之前没能发现的，而且是免费的，感谢您。但主题色调是否可以自主定制呢？最好是能附带背景还有页尾的颜色设置，还有就是列表页的宽度是否可以自定义数值呢？期待您的答复，祝平安吉祥。

**Comment by yrccondor** [comment]
很抱歉目前这些都不能自定义，但你可以通过自行修改 CSS 文件来自定义样式。
由于涉及到整体风格，这些选项短期内没有通过更新提供自定义选项的计划，但有仍可能会在未来被添加。

**Comment by swgqq** [comment]
很感谢您能及时回复，您说的可以自行修改CSS自定义样式，我做过尝试，但背景如果修改了，有切换夜间模式，背景无法随切换更改，所以比较灰心，但您说未来会被添加，很是期待，加油！
