### ISSUE TITLE
更换此主题后除主页外所有链接出现致命错误

### ISSUE THREAD

**Issue by LiiuKingming** [yrccondor/mdx#59]
开启DEBUG报错信息如下
Fatal error: Uncaught Error: Call to undefined function mb_strimwidth() in /usr/share/nginx/html/wordpress/wp-content/themes/mdx/functions.php:330 Stack trace: #0 /usr/share/nginx/html/wordpress/wp-content/themes/mdx/template-parts/content-first-2.php(4): mdx_get_post_excerpt(Object(WP_Post), 250) #1 /usr/share/nginx/html/wordpress/wp-includes/template.php(724): require('/usr/share/ngin...') #2 /usr/share/nginx/html/wordpress/wp-includes/template.php(671): load_template('/usr/share/ngin...', false) #3 /usr/share/nginx/html/wordpress/wp-includes/general-template.php(168): locate_template(Array, true, false) #4 /usr/share/nginx/html/wordpress/wp-content/themes/mdx/index.php(70): get_template_part('template-parts/...', '') #5 /usr/share/nginx/html/wordpress/wp-includes/template-loader.php(98): include('/usr/share/ngin...') #6 /usr/share/nginx/html/wordpress/wp-blog-header.php(19): require_once('/usr/share/ngin...') #7 /usr/share/nginx/html/wordpress/index.php(17): require('/usr/share/ngin...') #8 {main} thrown in /usr/share/nginx/html/wordpress/wp-content/themes/mdx/functions.php on line 330

**Comment by yrccondor** [comment]
@LiiuKingming 请参考文档 https://doc.flyhigher.top/mdx/zh-CN/tech/php-errors/ 修改你的 php 配置文件以开启此函数

**Comment by LiiuKingming** [comment]
Pattern not found:  ;extension=mbstring
找不到这个函数诶

**Comment by yrccondor** [comment]
可以告诉我你环境的详细信息吗？

**Comment by LiiuKingming** [comment]
数据库10.4.10-MariaDB   php版本7.3

**Comment by yrccondor** [comment]
@LiiuKingming 取决于你的系统，你可能需要安装额外的软件包来添加 mbstring 拓展。你可以自行搜索，一旦 mbstring 拓展被成功启用，MDx 应该可以正常运行
