### ISSUE TITLE
请问如何关闭文章中的内容纲要

### ISSUE THREAD

**Issue by joechenrh** [yrccondor/mdx#60]
![image](https://user-images.githubusercontent.com/18008525/70627718-a7275680-1c61-11ea-8712-b5dce9084133.png)
在设置里没有找到相关的选项:(，谢谢了

**Comment by yrccondor** [comment]
这不是 MDx 生成的内容，你可以检查一下你的插件等环境配置

**Comment by joechenrh** [comment]
好的，谢谢，我再去检查检查
