### ISSUE TITLE
网站元素显示不正常

### ISSUE THREAD

**Issue by CberYellowstone** [yrccondor/mdx#62]
更换域名后显示出现问题,如图
https://yellowstone.dns.army/wp-content/uploads/2020/01/TIM%E6%88%AA%E5%9B%BE20200103220621.png
但是在管理界面却没问题,如图
https://yellowstone.dns.army/wp-content/uploads/2020/01/TIM%E6%88%AA%E5%9B%BE20200103221402.png
安装方式是根目录安装
求解,谢谢(之前没换域名时用ip访问也有这个问题,和域名很有关)

**Comment by CberYellowstone** [comment]
可以的话也可以去我的博客实地考察一下https://yellowstone.dns.army/

**Comment by CberYellowstone** [comment]
还有实时搜索也用不了,我发誓开了要求打开的那个什么api,按照百度给的方法验证过api的开启了

**Comment by yrccondor** [comment]
是的，如果你打开浏览器控制台就会发现是因为跨域了，更新一下 Wordpress 数据库里的域名就好了，和 MDx 无关。
我这里测试你的实时搜索是正常的，要是有问题你可以自打开浏览器控制台看看有什么问题

**Comment by CberYellowstone** [comment]
@yrccondor 开发者您好,我已经把整个数据库内的旧域名替换成新域名了,但问题依旧,是不是mdx有什么额外的储存呢?

**Comment by CberYellowstone** [comment]
@yrccondor 抱歉,我想我找到问题的所在了,是一个缓存文件
/var/www/wordpress/wp-content/cache/all/index.html,
抱歉打扰到您了,在此道歉
