### ISSUE TITLE
文章分享只有国内社交媒体

### ISSUE THREAD

**Issue by florid2** [yrccondor/mdx#64]
在Sharing providers里面选择all或者Only providers outside China都不显示Telegram, Twitter, Facebook。 只有image excerpt sharing和国内部分。
![Capture](https://user-images.githubusercontent.com/25091279/72234461-42289d00-3621-11ea-9437-d7b53be9700a.PNG)

**Comment by florid2** [comment]
奇怪的是ios上看是好的，但是chrome桌面浏览器不显示国际社交媒体信息。
adblock没有屏蔽任何内容。不知道是不是bug。

**Comment by yrccondor** [comment]
这个功能应该是与浏览器无关的，你可以检查一下你的缓存相关设置

**Comment by florid2** [comment]
看来的确是缓存问题，多谢
