### ISSUE TITLE
请问怎么修改首页最上方照片的高度？

### ISSUE THREAD

**Issue by florid2** [yrccondor/mdx#65]
感谢这个开源项目，非常喜欢。
有个疑问，不知道在哪里调整首页顶上的照片的高度尺寸。
看到style.css里面有许多尺寸的定义，但是没法精确定位哪个值是针对这个图片的显示尺寸的。
我想把照片的高度缩小一点，请教怎么改。多谢了。

**Comment by yrccondor** [comment]
这牵扯到挺多样式的，你可以通过检查工具逐步修改。MDx 短时间内没有提供相关功能的计划

**Comment by florid2** [comment]
> 这牵扯到挺多样式的，你可以通过检查工具逐步修改。MDx 短时间内没有提供相关功能的计划

不好意思多问一句，检查工具是wordpress的一个插件还是浏览器的工具？

**Comment by yrccondor** [comment]
是指浏览器的检查工具。
没有最佳尺寸，图片会根据不同屏幕大小被裁剪。

**Comment by Sn0bzy** [comment]
1920x600像素是标头照片的最佳尺寸。 480x550像素最适合移动设备视图（如果您使用的是通知部分)。
