### ISSUE TITLE
国际版评论发送成功还是显示中文

### ISSUE THREAD

**Issue by florid2** [yrccondor/mdx#66]
英文的wordpress环境，其他显示都正常。
在测试发表评论时发现，发送评论后在头顶显示“发射成功”。似乎在国际化上遗漏了这个消息。
需要修改ajax-comment/app.js。

**Comment by yrccondor** [comment]
已确认，稍后修复

**Comment by yrccondor** [comment]
已于 2f2cfaa 修复，更新稍后发布
