### ISSUE TITLE
更新1.9.6版本后图片无法正常显示

### ISSUE THREAD

**Issue by YuzeZhang** [yrccondor/mdx#73]
更新之后包括文章特色图片、首页图片、抽屉菜单顶部图片、文章内插入的图片都不显示了TAT

**Comment by yrccondor** [comment]
1.9.6 并没有动过相关逻辑，你可以看看浏览器检查工具也没有报任何错误

**Comment by yrccondor** [comment]
检查之后的确发现有问题，仅在禁用夜间模式或启用黑暗主题后出现，我会尽快修复

**Comment by YuzeZhang** [comment]
是的！禁用黑暗主题并启用夜间模式之后图片就正常了！大佬👍

**Comment by yrccondor** [comment]
已于 e737324 修复，1.9.7 明天更新

**Comment by florid2** [comment]
1.9.7 文章中有多张照片的情况下还是有部分图片无法正常显示。
Lazy Load Images设置
Prioritize Speed: 部分图片不显示，出现一个灰色的图片框，中间一直在转圈。
Prioritize SEO (Medium): 选这个的话，全部图片可以正常显示。目前只能设置在这个档位。

**Comment by yrccondor** [comment]
@florid2 你可以检查一下是否是和 #74 一样的问题。
