### ISSUE TITLE
1.9.7后的一些报错是否正常？

### ISSUE THREAD

**Issue by florid2** [yrccondor/mdx#74]
升级1.9.7后，在chrome的develop tools里面发现不少报错，不知道这个是否正常。请看下面截图和log，多谢。

![Capture](https://user-images.githubusercontent.com/25091279/73702468-f90bca80-4740-11ea-8b58-65e4c066f057.PNG)

[1580775720108.log](https://github.com/yrccondor/mdx/files/4150831/1580775720108.log)

**Comment by florid2** [comment]
PS: 把cloudflare的rocket-loader关了还是这些地方报错，似乎不是rocket loader和js的兼容性问题。
![Capture2](https://user-images.githubusercontent.com/25091279/73703825-602b7e00-4745-11ea-8f9f-f8126e2ef2e3.PNG)

**Comment by yrccondor** [comment]
看了下，应该是由于相关语句的英文翻译中包含引号导致语法错误了。我会尽快联系英文翻译维护者更新翻译

**Comment by yechs** [comment]
啊好的，用 `&quot;` escape 掉就好
我马上去fix
