### ISSUE TITLE
New Header Styles

### ISSUE THREAD

**Issue by Sn0bzy** [yrccondor/mdx#75]
Now we can use only static header style. If you can add different styles it can be better.

I think slider will be good for start. I created one example. Control buttons, article name, article description, category, author and view counter added. 

Example:
![Slider Advice](https://www.imageupload.net/upload-image/2020/02/04/Slider-Advice.png)

**Comment by Sn0bzy** [comment]
It can be used in two different ways. The first one will auto-shoot recent posts. Second, posts in the selected category will be shown. If the second option is selected, the text category section above will be hidden.

**Comment by Sn0bzy** [comment]
Can you do this @yrccondor ?

**Comment by yrccondor** [comment]
well, actually i have a similar plan, but the dynamic banner will be included in a new home page style only, which will be finished later.
**however, after you opened this issue, i'm now considering to make this as a general opinion for all home page styles as you mentioned above.** it may take some time , so stay tuned :-)

**Comment by Sn0bzy** [comment]
I'm glad to hear that. I follow the developments closely :)
