### ISSUE TITLE
手机版页面推荐文章的四角不圆

### ISSUE THREAD

**Issue by florid2** [yrccondor/mdx#78]
桌面版首页的推荐文章显示正常。
移动手机版页面的首页推荐文章四个角缺少弧度，与下面文章块样式不一致。
![8E26DE3E-25B3-44F4-8FF0-E589E8A11E51](https://user-images.githubusercontent.com/25091279/74323070-0710b980-4dd9-11ea-8c0b-b3f0dc79b315.jpeg)

**Comment by yrccondor** [comment]
未能复现。如果方便的话，可以告诉我出现问题的页面地址吗？

**Comment by florid2** [comment]
https://xfelix.com
用ios手机safari访问

**Comment by yrccondor** [comment]
在 ios 13 的 safari 上成功复现，但 ios 12 上的 safari 和其他浏览器似乎都没有这一问题，可能是 safari 的问题，我还在寻找原因。
顺便问一下，在 macos 版的 safari 中有同样的问题吗？

**Comment by florid2** [comment]
让别人用macos(10.15.2)的safari访问了一下，没有此问题。
我家已经停电一周了，没电没网，自己的macos无法测试。
也许是ios13的bug？

**Comment by yrccondor** [comment]
目前来看，似乎是 ios 13 上的 safari 处理 overflow 时行为改变带来的 Bug。我会尝试修复，但因为调试比较困难，这个问题不一定能被马上修复。

**Comment by yrccondor** [comment]
折腾了一天了以后我现在确定是 ios 13 safari 在部分情况下对于拥有相同 z-index 的两个元素的处理有问题，进而会导致一些渲染问题。我暂时没能构建出一个最小复现 demo，但 MDx 中的问题应该可以修复了。你现在可以尝试访问 https://mdxblog.flyhigher.top 看看还没有相同的问题。

**Comment by florid2** [comment]
@yrccondor 你的站现在ios safari访问显示正常的

**Comment by florid2** [comment]
@yrccondor 一个有意思的发现
我把我的站升级到1.9.8后用手机ios safari发现还是四个直角，怀疑是不是cache的关系，换了ipad访问，四个角是圆的。
然后又换了台iPhone手机，竖屏的时候显示直角，横屏的时候显示圆角。
但是我自己的iPhone不管横竖屏还都显示直角，估计还是缓存的问题。
这下更确信是ios的显示处理bug了。

**Comment by yrccondor** [comment]
之前我在食堂修复这问题的时候，我在 iPhone 11, Xs, X 上测试过，也包括你的设备，均能稳定复现问题，修改后问题也都全部消失。
有意思
