### ISSUE TITLE
Add a New Function: TOC

### ISSUE THREAD

**Issue by da3rdev** [yrccondor/mdx#79]
I found mdx took on a new look after updating, right behind I decided to write the blog again.

New appearance did amaze me, but still, there is not a function such called TOC (Table of contents).

![image](https://user-images.githubusercontent.com/15688641/74455311-161e6700-4ec0-11ea-8733-fecb042c4a48.png)

So the issue is to encourage Axton (the gorgeous guy) to write this function. if he doesn't, I may write one by myself when I feel like doing it. 

Thanks for developing such a beautiful theme.

**Comment by yrccondor** [comment]
well, MDx now has a bulit-in TOC, but it has been hidden in the main ui. just click the menu button when you are browsing an article and you can find the TOC. please notice that only when the article has correct titles (`h1`, `h2` & `h3`) can MDx show a proper TOC.

**Comment by yrccondor** [comment]
btw, if you have any suggestion about where to place the TOC, please let me know.

**Comment by da3rdev** [comment]
sry for the inconvenience caused by my carelessness, and I am sure I'll keep watching this project.
love u babe
❤️

**Comment by da3rdev** [comment]
well, an idea just passed my mind, the TOC can be put in the right/ left side of the main article body,
![image](https://user-images.githubusercontent.com/15688641/74461388-69e17e00-4ec9-11ea-8537-5fc4b1d940ca.png)

like _juejin.im_:
![image](https://user-images.githubusercontent.com/15688641/74461417-79f95d80-4ec9-11ea-9cce-64b0f0ee2949.png)

in this way to display TOC, readers can easily locate the place where they are reading.

**Comment by yrccondor** [comment]
actually i've thought about that, but MDx is a single column theme, so that doesn't look good. I'm still looking for a better sulotion.
