### ISSUE TITLE
首页图片无法显示的bug

### ISSUE THREAD

**Issue by zenyanbo** [yrccondor/mdx#80]
在“MDx 主题 - 样式 - 首页样式”中选择简单后。首页图片的选项就会失效成为纯色背景。

如图
![批注 2020-02-16 175615](https://user-images.githubusercontent.com/34698908/74602634-b2758300-50e5-11ea-9f34-ebcb83de4b85.png)

**Comment by yrccondor** [comment]
这不是 bug，“简单”首页样式本来就是这么设计的😅

**Comment by dophys** [comment]
原来是这样。我把您文章页的特色图片当作了首页的首图，我说怎么关了其他插件就死活设置不成功呢。

**Comment by jeeinn** [comment]
建议在设置项提醒一下
很棒的主题！

**Comment by yrccondor** [comment]
@jeeinn 会在之后的更新中加提示的
