### ISSUE TITLE
独立页面在不设置图片时顶部始终有未加载完成的进度条

### ISSUE THREAD

**Issue by LaMP57** [yrccondor/mdx#83]
在登陆状态下进度条会被顶部管理工具条挡住，未登录状态下可见。

![image](https://user-images.githubusercontent.com/21251711/75106351-a003c800-5656-11ea-860a-666f0bdf622e.png)

**Comment by yrccondor** [comment]
已于 cefd563 修复，稍后推送更新

**Comment by LaMP57** [comment]
感谢
