### ISSUE TITLE
1.9.9 cookie consent not properly disabled

### ISSUE THREAD

**Issue by x-Felix** [yrccondor/mdx#87]
升级到1.9.9后发现首页右下角出现了块‘膏药’
<img width="604" alt="Screen Shot 2020-02-27 at 11 52 45" src="https://user-images.githubusercontent.com/25091279/75402082-1145c280-5958-11ea-9db7-d76807acd2aa.png">
怀疑是不是确认cookie的，因为没有内容，不知道哪里来的。
然后又查了一遍设置菜单，发现有个新功能叫做Cookies consent (GDPR compliance)，但是按照提示，如果留白的话，这个功能是disable的（Edit cookies consent here, HTML supported. Leave it blank to disable.）。但是似乎disable没成功。

**Comment by yrccondor** [comment]
是的，目前来看是因为更新时这一功能的初始值没能正常写入导致这个值在读取时其实不为空。我正在寻找原因。
要解决很简单，只要到 MDx 主题-功能页面重新保存一遍就好了，这会往设置中写入正确的值。
