### ISSUE TITLE
Traditional Chinese Support

### ISSUE THREAD

**Issue by AngelKitty** [yrccondor/mdx#88]
Hi, I'm planning to translate the site into Traditional Chinese, and I've checked files inside the language directory (tl_TR.mo, tl_TR.po, en_US.mo and en_US.po), I will help you if you need this service.

**Comment by yrccondor** [comment]
Yes, we would appreciate it if you could help us. Feel free to ask us if you have any questions.

**Comment by yechs** [comment]
@yrccondor Actually I think it would be best if we can create a `.POT` template file that centrally stores all strings that need to be translated. 
It would make language version management easier and reduce redundant efforts for translators of different languages.

**Comment by yrccondor** [comment]
@yechs Great idea, I'll try to generate a `.POT` template in future updates.
