### ISSUE TITLE
在暗黑模式下，PNG、SVG格式的图片可能难以阅读

### ISSUE THREAD

**Issue by HixGitHub** [yrccondor/mdx#92]
使用 QuickLaTeX 插件来编辑公式时，公式会以SVG格式显示。而背景与图片中的文字都是黑色，导致难以阅读。

**Comment by yrccondor** [comment]
对于透明背景的图像，这是正常情况，主题应该呈现图片本来的样子而不是自作主张地优化，我们也不可能为了公式显示这一个需求进行单独优化。
你可以自行编写 css 来使 svg 显示白色（参考 https://flyhigher.top）。

**Comment by HixGitHub** [comment]
感谢回复。改CSS后是可以得到较好的视觉效果的，谢谢 : )
