### ISSUE TITLE
希望主题在页尾部分增加社交直接连接的按钮

### ISSUE THREAD

**Issue by debuginn** [yrccondor/mdx#93]
建议在备案号上面添加，光是按钮的排列显示，跟随主体颜色，既大方有美观简洁
添加社交图标：微博、微信、Telegram、Twitter、Facebook、Bilibili、网易云音乐、知乎

当然，以上是可以进行选择的，可以选择性显示

**Comment by yrccondor** [comment]
已添加此功能
