### ISSUE TITLE
菜单中文字丢失

### ISSUE THREAD

**Issue by hmsjy2017** [yrccondor/mdx#96]
![EFE1A465-07BB-46C6-8DC8-82BDD2884430](https://user-images.githubusercontent.com/42692274/77807125-cd162100-70c1-11ea-9ee7-8aa8f0fa8afe.png)
如图所示，菜单中有两项文字丢失，同时后面还多了“···”，经多次确认，配置正确。请问如何解决？

**Comment by yrccondor** [comment]
你没有按文档正确配置，请参考文档

**Comment by hmsjy2017** [comment]
文档读过，并且也是完全按照文档中的步骤进行配置，换成其他图标均能正常显示仅在使用这两个图标时会出现问题。

**Comment by yrccondor** [comment]
我没有复现相关问题，你在这几项菜单中中填写的内容是？

**Comment by hmsjy2017** [comment]
<i class="mdui-icon material-icons">label_outline</i> 标签
<i class="mdui-icon material-icons">info_outline</i> 关于
中间是有一个空格的

**Comment by yrccondor** [comment]
确认这是 Google 提供的字体文件和 MDUI 字体文件的少数几个图标冲突造成的，我会尽量修复。在此之前，你可以通过禁用 MD2 风格来禁用 Google 字体或更换图标来解决问题

**Comment by yrccondor** [comment]
已于 44962a9 修复
