### ISSUE TITLE
用户头像无法显示

### ISSUE THREAD

**Issue by hmsjy2017** [yrccondor/mdx#97]
评论区中，用户头像无法显示。
![BD21C5BF-FCC6-4A08-A0A9-86C09F5DD085](https://user-images.githubusercontent.com/42692274/78235063-a402ef80-750a-11ea-9396-deb6ad20a340.png)

**Comment by yrccondor** [comment]
网络问题，请自行解决。
![image](https://user-images.githubusercontent.com/14820835/78235358-1d9add80-750b-11ea-9aff-6bacf3669c95.png)

**Comment by hmsjy2017** [comment]
个人认为，Gravatar 头像可使用国内加速服务，比如gravatar.loli.net，能有效解决头像无法显示的问题。

**Comment by yrccondor** [comment]
@hmsjy2017 我知道有代理可用，但这超出了 MDx 的负责范围，使用插件或自己改代码更合适，MDx 不会为此做特殊优化

**Comment by hmsjy2017** [comment]
好的
